-- Gaming Gear E-Commerce schema (generated by apps/api/scripts/gen-sql.ts - do not edit by hand)
-- Run this whole file once in Supabase > SQL Editor on an empty database.
-- Seeded admin login: admin@gaminggear.local / admin1234

-- CreateSchema
CREATE SCHEMA IF NOT EXISTS "public";

-- CreateEnum
CREATE TYPE "Role" AS ENUM ('customer', 'admin');

-- CreateEnum
CREATE TYPE "OrderStatus" AS ENUM ('pending_payment', 'payment_review', 'processing', 'shipped', 'delivered', 'cancelled');

-- CreateEnum
CREATE TYPE "PaymentStatus" AS ENUM ('pending', 'approved', 'rejected');

-- CreateTable
CREATE TABLE "users" (
    "user_id" SERIAL NOT NULL,
    "full_name" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "password_hash" TEXT NOT NULL,
    "phone" TEXT,
    "role" "Role" NOT NULL DEFAULT 'customer',
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "users_pkey" PRIMARY KEY ("user_id")
);

-- CreateTable
CREATE TABLE "addresses" (
    "address_id" SERIAL NOT NULL,
    "user_id" INTEGER NOT NULL,
    "recipient_name" TEXT NOT NULL,
    "phone" TEXT NOT NULL,
    "address_line" TEXT NOT NULL,
    "is_default" BOOLEAN NOT NULL DEFAULT false,

    CONSTRAINT "addresses_pkey" PRIMARY KEY ("address_id")
);

-- CreateTable
CREATE TABLE "password_reset_tokens" (
    "token" TEXT NOT NULL,
    "user_id" INTEGER NOT NULL,
    "expires_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "password_reset_tokens_pkey" PRIMARY KEY ("token")
);

-- CreateTable
CREATE TABLE "categories" (
    "category_id" SERIAL NOT NULL,
    "category_name" TEXT NOT NULL,

    CONSTRAINT "categories_pkey" PRIMARY KEY ("category_id")
);

-- CreateTable
CREATE TABLE "products" (
    "product_id" SERIAL NOT NULL,
    "category_id" INTEGER,
    "sku" TEXT NOT NULL,
    "product_name" TEXT NOT NULL,
    "description" TEXT NOT NULL DEFAULT '',
    "details" TEXT NOT NULL DEFAULT '',
    "highlights" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "specs" JSONB NOT NULL DEFAULT '[]',
    "price" DECIMAL(10,2) NOT NULL,
    "stock_quantity" INTEGER NOT NULL DEFAULT 0,
    "image_url" TEXT,
    "is_active" BOOLEAN NOT NULL DEFAULT true,

    CONSTRAINT "products_pkey" PRIMARY KEY ("product_id")
);

-- CreateTable
CREATE TABLE "product_images" (
    "image_id" SERIAL NOT NULL,
    "product_id" INTEGER NOT NULL,
    "image_url" TEXT NOT NULL,
    "sort_order" INTEGER NOT NULL DEFAULT 0,

    CONSTRAINT "product_images_pkey" PRIMARY KEY ("image_id")
);

-- CreateTable
CREATE TABLE "carts" (
    "cart_id" SERIAL NOT NULL,
    "user_id" INTEGER NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "carts_pkey" PRIMARY KEY ("cart_id")
);

-- CreateTable
CREATE TABLE "cart_items" (
    "cart_item_id" SERIAL NOT NULL,
    "cart_id" INTEGER NOT NULL,
    "product_id" INTEGER NOT NULL,
    "quantity" INTEGER NOT NULL,

    CONSTRAINT "cart_items_pkey" PRIMARY KEY ("cart_item_id")
);

-- CreateTable
CREATE TABLE "orders" (
    "order_id" SERIAL NOT NULL,
    "user_id" INTEGER NOT NULL,
    "order_date" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "status" "OrderStatus" NOT NULL DEFAULT 'pending_payment',
    "shipping_name" TEXT NOT NULL,
    "shipping_phone" TEXT NOT NULL,
    "shipping_address" TEXT NOT NULL,
    "shipping_method" TEXT NOT NULL,
    "tracking_number" TEXT,
    "shipping_fee" DECIMAL(10,2) NOT NULL DEFAULT 0,

    CONSTRAINT "orders_pkey" PRIMARY KEY ("order_id")
);

-- CreateTable
CREATE TABLE "order_items" (
    "order_item_id" SERIAL NOT NULL,
    "order_id" INTEGER NOT NULL,
    "product_id" INTEGER NOT NULL,
    "quantity" INTEGER NOT NULL,
    "unit_price" DECIMAL(10,2) NOT NULL,

    CONSTRAINT "order_items_pkey" PRIMARY KEY ("order_item_id")
);

-- CreateTable
CREATE TABLE "payments" (
    "payment_id" SERIAL NOT NULL,
    "order_id" INTEGER NOT NULL,
    "payment_method" TEXT NOT NULL,
    "amount" DECIMAL(10,2) NOT NULL,
    "status" "PaymentStatus" NOT NULL DEFAULT 'pending',
    "proof_url" TEXT,
    "paid_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "payments_pkey" PRIMARY KEY ("payment_id")
);

-- CreateTable
CREATE TABLE "reviews" (
    "review_id" SERIAL NOT NULL,
    "user_id" INTEGER NOT NULL,
    "product_id" INTEGER NOT NULL,
    "rating" INTEGER NOT NULL,
    "comment" TEXT NOT NULL DEFAULT '',
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "reviews_pkey" PRIMARY KEY ("review_id")
);

-- CreateIndex
CREATE UNIQUE INDEX "users_email_key" ON "users"("email");

-- CreateIndex
CREATE UNIQUE INDEX "categories_category_name_key" ON "categories"("category_name");

-- CreateIndex
CREATE UNIQUE INDEX "products_sku_key" ON "products"("sku");

-- CreateIndex
CREATE INDEX "product_images_product_id_sort_order_idx" ON "product_images"("product_id", "sort_order");

-- CreateIndex
CREATE UNIQUE INDEX "carts_user_id_key" ON "carts"("user_id");

-- CreateIndex
CREATE UNIQUE INDEX "cart_items_cart_id_product_id_key" ON "cart_items"("cart_id", "product_id");

-- CreateIndex
CREATE UNIQUE INDEX "reviews_user_id_product_id_key" ON "reviews"("user_id", "product_id");

-- AddForeignKey
ALTER TABLE "addresses" ADD CONSTRAINT "addresses_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("user_id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "password_reset_tokens" ADD CONSTRAINT "password_reset_tokens_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("user_id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "products" ADD CONSTRAINT "products_category_id_fkey" FOREIGN KEY ("category_id") REFERENCES "categories"("category_id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "product_images" ADD CONSTRAINT "product_images_product_id_fkey" FOREIGN KEY ("product_id") REFERENCES "products"("product_id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "carts" ADD CONSTRAINT "carts_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("user_id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "cart_items" ADD CONSTRAINT "cart_items_cart_id_fkey" FOREIGN KEY ("cart_id") REFERENCES "carts"("cart_id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "cart_items" ADD CONSTRAINT "cart_items_product_id_fkey" FOREIGN KEY ("product_id") REFERENCES "products"("product_id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "orders" ADD CONSTRAINT "orders_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("user_id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "order_items" ADD CONSTRAINT "order_items_order_id_fkey" FOREIGN KEY ("order_id") REFERENCES "orders"("order_id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "order_items" ADD CONSTRAINT "order_items_product_id_fkey" FOREIGN KEY ("product_id") REFERENCES "products"("product_id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "payments" ADD CONSTRAINT "payments_order_id_fkey" FOREIGN KEY ("order_id") REFERENCES "orders"("order_id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "reviews" ADD CONSTRAINT "reviews_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("user_id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "reviews" ADD CONSTRAINT "reviews_product_id_fkey" FOREIGN KEY ("product_id") REFERENCES "products"("product_id") ON DELETE CASCADE ON UPDATE CASCADE;


-- ===== Seed data =====
INSERT INTO "users" ("full_name", "email", "password_hash", "phone", "role") VALUES ('Admin', 'admin@gaminggear.local', '$2b$10$aY4jDVALN0joWDrgWbBtVecn2NDWqjUrRjhSQC3vCArPX4l3jHOeS', '0800000000', 'admin') ON CONFLICT ("email") DO NOTHING;

INSERT INTO "categories" ("category_name") VALUES ('Mouse') ON CONFLICT DO NOTHING;
INSERT INTO "categories" ("category_name") VALUES ('Keyboard') ON CONFLICT DO NOTHING;
INSERT INTO "categories" ("category_name") VALUES ('Headset') ON CONFLICT DO NOTHING;
INSERT INTO "categories" ("category_name") VALUES ('Monitor') ON CONFLICT DO NOTHING;
INSERT INTO "categories" ("category_name") VALUES ('Chair') ON CONFLICT DO NOTHING;
INSERT INTO "categories" ("category_name") VALUES ('Controller') ON CONFLICT DO NOTHING;

INSERT INTO "products" ("category_id", "sku", "product_name", "description", "price", "stock_quantity", "image_url", "details", "highlights", "specs") SELECT "category_id", 'MS-001', 'Logitech G Pro X Superlight 2', 'เมาส์ไร้สายน้ำหนักเบาเพียง 60 กรัม เซนเซอร์ HERO 2 ความละเอียดสูงสุด 44,000 DPI', 5290, 25, '/products/ms-001.jpg', 'Logitech G Pro X Superlight 2 คือเมาส์ไร้สายรุ่นเรือธงที่ออกแบบร่วมกับนักกีฬาอีสปอร์ตมืออาชีพ ด้วยน้ำหนักเพียง 60 กรัม ทำให้สะบัดเมาส์ได้เร็วและแม่นยำโดยแทบไม่รู้สึกถึงน้ำหนัก เหมาะอย่างยิ่งกับเกม FPS ที่ต้องการการเล็งที่รวดเร็ว

หัวใจสำคัญคือเซนเซอร์ HERO 2 ที่รองรับความละเอียดสูงสุด 44,000 DPI และติดตามการเคลื่อนไหวได้มากกว่า 888 IPS ทำงานร่วมกับการเชื่อมต่อไร้สาย LIGHTSPEED ที่รองรับ polling rate สูงสุด 8,000 Hz ให้การตอบสนองที่ลื่นไหลไม่แพ้เมาส์มีสาย

ปุ่มคลิกใช้สวิตช์ LIGHTFORCE แบบไฮบริดออปติคัล-แมคคานิคัล ที่ได้ทั้งความเร็วของสวิตช์ออปติคัลและสัมผัสการคลิกแบบแมคคานิคัล พร้อมแบตเตอรี่ที่ใช้งานต่อเนื่องได้สูงสุด 95 ชั่วโมง ชาร์จผ่านสาย USB-C', ARRAY['เซนเซอร์ HERO 2 ความละเอียดสูงสุด 44,000 DPI ติดตามได้มากกว่า 888 IPS', 'ไร้สาย LIGHTSPEED รองรับ polling rate สูงสุด 8,000 Hz', 'น้ำหนักเพียง 60 กรัม', 'สวิตช์ LIGHTFORCE แบบไฮบริด ทนทาน 70 ล้านคลิก', 'ฟีตเมาส์ PTFE ไร้สารเติมแต่ง ลื่นไหลทุกการเคลื่อนไหว', 'แบตเตอรี่ใช้งานได้สูงสุด 95 ชั่วโมง']::text[], '[{"label":"เซนเซอร์","value":"HERO 2"},{"label":"ความละเอียด","value":"100 – 44,000 DPI"},{"label":"ความเร็วสูงสุด","value":"มากกว่า 888 IPS"},{"label":"ความเร่งสูงสุด","value":"มากกว่า 88 G"},{"label":"Polling rate","value":"สูงสุด 8,000 Hz (0.125 ms)"},{"label":"การเชื่อมต่อ","value":"LIGHTSPEED ไร้สาย (มีสายชาร์จ USB-C)"},{"label":"แบตเตอรี่","value":"สูงสุด 95 ชั่วโมง"},{"label":"สวิตช์","value":"LIGHTFORCE hybrid optical-mechanical, 70 ล้านคลิก"},{"label":"จำนวนปุ่ม","value":"5 ปุ่ม"},{"label":"น้ำหนัก","value":"60 กรัม"},{"label":"ขนาด (ย × ก × ส)","value":"125 × 63.5 × 40 มม."}]'::jsonb FROM "categories" WHERE "category_name" = 'Mouse' ON CONFLICT ("sku") DO NOTHING;
INSERT INTO "products" ("category_id", "sku", "product_name", "description", "price", "stock_quantity", "image_url", "details", "highlights", "specs") SELECT "category_id", 'MS-002', 'Razer DeathAdder V3', 'เมาส์ทรง ergonomic ยอดนิยมสำหรับเกม FPS เซนเซอร์ Focus Pro 30K', 2690, 40, '/products/ms-002.jpg', 'Razer DeathAdder V3 คือเมาส์เกมมิ่งแบบมีสายที่ต่อยอดจากตระกูล DeathAdder ซึ่งเป็นหนึ่งในทรงเมาส์ที่ได้รับความนิยมสูงสุดในวงการ รุ่นนี้ปรับทรง ergonomic สำหรับมือขวาให้กระชับขึ้น และลดน้ำหนักลงเหลือเพียง 59 กรัม เบากว่ารุ่นก่อนมากกว่า 25%

ภายในใช้เซนเซอร์ Razer Focus Pro 30K ความละเอียดสูงสุด 30,000 DPI พร้อมเทคโนโลยี HyperPolling ที่รองรับ polling rate สูงสุด 8,000 Hz ส่งข้อมูลการเคลื่อนไหวถี่ขึ้นเพื่อความลื่นไหลบนจอรีเฟรชเรตสูง

สวิตช์ออปติคัล Gen-3 ไม่มีปัญหาดับเบิลคลิกและทนทานถึง 90 ล้านคลิก ส่วนสาย Razer SpeedFlex ยาว 1.8 เมตรนิ่มและเบา ให้ความรู้สึกใกล้เคียงเมาส์ไร้สาย', ARRAY['HyperPolling รองรับ polling rate สูงสุด 8,000 Hz', 'เซนเซอร์ Focus Pro 30K ความละเอียดสูงสุด 30,000 DPI', 'น้ำหนักเพียง 59 กรัม เบากว่ารุ่นก่อนกว่า 25%', 'สวิตช์ออปติคัล Gen-3 ทนทาน 90 ล้านคลิก', 'ทรง ergonomic สำหรับมือขวา จับถนัดทั้ง palm และ claw grip', 'บันทึกโปรไฟล์ในตัวเมาส์ได้ 5 โปรไฟล์']::text[], '[{"label":"เซนเซอร์","value":"Razer Focus Pro 30K Optical"},{"label":"ความละเอียดสูงสุด","value":"30,000 DPI"},{"label":"ความเร็วสูงสุด","value":"750 IPS"},{"label":"ความเร่งสูงสุด","value":"70 G"},{"label":"Polling rate","value":"สูงสุด 8,000 Hz (0.125 ms)"},{"label":"การเชื่อมต่อ","value":"มีสาย Razer SpeedFlex ยาว 1.8 ม."},{"label":"สวิตช์","value":"Razer Optical Gen-3, 90 ล้านคลิก"},{"label":"ปุ่มที่ตั้งค่าได้","value":"6 ปุ่ม"},{"label":"ฟีตเมาส์","value":"PTFE 100%"},{"label":"น้ำหนัก","value":"59 กรัม"},{"label":"ขนาด (ย × ก × ส)","value":"128 × 68 × 44 มม."}]'::jsonb FROM "categories" WHERE "category_name" = 'Mouse' ON CONFLICT ("sku") DO NOTHING;
INSERT INTO "products" ("category_id", "sku", "product_name", "description", "price", "stock_quantity", "image_url", "details", "highlights", "specs") SELECT "category_id", 'MS-003', 'Zowie EC2-C', 'เมาส์สายสำหรับ eSports ไม่ต้องลงไดรเวอร์ รูปทรงถนัดขวา', 2390, 0, '/products/ms-003.jpg', 'Zowie EC2-C คือเมาส์ทรง ergonomic ขนาดกลางสำหรับมือขวา ที่นักกีฬาอีสปอร์ตสาย FPS เลือกใช้มาอย่างยาวนาน จุดเด่นคือความเรียบง่ายแบบ plug and play เสียบใช้งานได้ทันทีโดยไม่ต้องติดตั้งไดรเวอร์หรือซอฟต์แวร์ใดๆ ปรับค่าทุกอย่างได้จากปุ่มบนตัวเมาส์

รุ่น C เป็นเวอร์ชันปรับปรุงที่ลดน้ำหนักลงเหลือ 73 กรัม และเปลี่ยนมาใช้สายแบบ paracord ที่นิ่มและยืดหยุ่น ลดแรงต้านเวลาลากเมาส์ ขณะที่ลูกกลิ้ง 24 จังหวะให้สัมผัสชัดเจนทุกครั้งที่หมุน เหมาะกับการเปลี่ยนอาวุธในเกม

ภายในใช้เซนเซอร์ 3360 ที่ขึ้นชื่อเรื่องความแม่นยำ เลือก DPI ได้ 4 ระดับ และตั้งค่าความเร็วการตอบสนองของปุ่มคลิกได้ทั้งแบบ Fast และ Normal', ARRAY['ทรง ergonomic ขนาดกลาง จับถนัดมือ เหมาะกับการเล่นยาวๆ', 'Plug and play ไม่ต้องลงไดรเวอร์หรือซอฟต์แวร์', 'น้ำหนักเบา 73 กรัม พร้อมสาย paracord นิ่ม ลดแรงต้าน', 'ลูกกลิ้ง 24 จังหวะ สัมผัสชัดเจนทุกสเต็ป', 'เลือกความเร็วการตอบสนองของคลิกได้ (Fast / Normal)']::text[], '[{"label":"เซนเซอร์","value":"3360"},{"label":"DPI","value":"400 / 800 / 1600 / 3200"},{"label":"Polling rate","value":"125 / 500 / 1000 Hz"},{"label":"การเชื่อมต่อ","value":"มีสาย USB 2.0 / 3.0 ไม่ต้องลงไดรเวอร์"},{"label":"สาย","value":"สายนิ่มแบบ paracord"},{"label":"จำนวนปุ่ม","value":"5 ปุ่ม"},{"label":"ลูกกลิ้ง","value":"24 จังหวะ"},{"label":"ขนาด","value":"Medium"},{"label":"น้ำหนัก","value":"73 กรัม (ไม่รวมสาย)"}]'::jsonb FROM "categories" WHERE "category_name" = 'Mouse' ON CONFLICT ("sku") DO NOTHING;
INSERT INTO "products" ("category_id", "sku", "product_name", "description", "price", "stock_quantity", "image_url", "details", "highlights", "specs") SELECT "category_id", 'MS-004', 'SteelSeries Aerox 3 Wireless', 'เมาส์ไร้สายกันน้ำกันฝุ่น IP54 ดีไซน์รังผึ้ง', 2990, 18, '/products/ms-004.jpg', 'SteelSeries Aerox 3 Wireless คือเมาส์ไร้สายน้ำหนักเบาที่มาพร้อมดีไซน์บอดี้รังผึ้งเป็นเอกลักษณ์ น้ำหนักเพียง 68 กรัม แต่ยังทนทานกว่าที่คิด ด้วยมาตรฐานกันน้ำกันฝุ่น IP54 จากเทคโนโลยี AquaBarrier ที่ปกป้องชิ้นส่วนภายในจากฝุ่น สิ่งสกปรก และละอองน้ำ

รองรับการเชื่อมต่อสองรูปแบบ คือไร้สาย Quantum 2.0 ความถี่ 2.4 GHz สำหรับการเล่นเกมที่ต้องการความหน่วงต่ำ และ Bluetooth 5.0 สำหรับใช้งานทั่วไปพร้อมแบตเตอรี่ที่อยู่ได้นานถึง 200 ชั่วโมง

เซนเซอร์ TrueMove Air ปรับความละเอียดได้ตั้งแต่ 100 ถึง 18,000 CPI พร้อมไฟ RGB 3 โซนที่ส่องผ่านบอดี้ และฟีต PTFE เกรดบริสุทธิ์ที่ช่วยให้เลื่อนได้ลื่นไหล', ARRAY['กันน้ำกันฝุ่นระดับ IP54 ด้วยเทคโนโลยี AquaBarrier', 'เชื่อมต่อได้ทั้ง 2.4 GHz Quantum 2.0 และ Bluetooth 5.0', 'แบตเตอรี่สูงสุด 200 ชั่วโมง (Bluetooth)', 'บอดี้รังผึ้ง น้ำหนักเบาเพียง 68 กรัม', 'ไฟ RGB 3 โซน', 'ฟีต PTFE เกรดบริสุทธิ์ 100%']::text[], '[{"label":"เซนเซอร์","value":"SteelSeries TrueMove Air (optical)"},{"label":"ความละเอียด","value":"100 – 18,000 CPI"},{"label":"ความเร็วสูงสุด","value":"400 IPS"},{"label":"ความเร่ง","value":"40 G"},{"label":"Polling rate","value":"1,000 Hz"},{"label":"การเชื่อมต่อ","value":"2.4 GHz Quantum 2.0 / Bluetooth 5.0 / USB-C"},{"label":"แบตเตอรี่","value":"สูงสุด 80 ชม. (2.4 GHz), 200 ชม. (Bluetooth)"},{"label":"สวิตช์","value":"Golden Micro IP54, 80 ล้านคลิก"},{"label":"มาตรฐานกันน้ำกันฝุ่น","value":"IP54"},{"label":"น้ำหนัก","value":"68 กรัม"}]'::jsonb FROM "categories" WHERE "category_name" = 'Mouse' ON CONFLICT ("sku") DO NOTHING;
INSERT INTO "products" ("category_id", "sku", "product_name", "description", "price", "stock_quantity", "image_url", "details", "highlights", "specs") SELECT "category_id", 'KB-001', 'Wooting 60HE+', 'คีย์บอร์ดแม่เหล็ก Hall Effect ปรับระยะกดได้ รองรับ Rapid Trigger', 7490, 10, '/products/kb-001.jpg', 'Wooting 60HE+ คือคีย์บอร์ดขนาด 60% ที่เปลี่ยนมาตรฐานคีย์บอร์ดเกมมิ่งไปตลอดกาล ด้วยสวิตช์แม่เหล็ก Hall Effect ที่วัดได้ว่าแต่ละปุ่มถูกกดลงไปลึกเท่าไร ทำให้ปรับจุดทำงาน (actuation) ได้ทุกปุ่มอย่างละเอียดตั้งแต่ 0.1 ถึง 4.0 มม.

Wooting คือผู้ริเริ่มฟีเจอร์ Rapid Trigger ที่ปุ่มจะรีเซ็ตทันทีที่เริ่มปล่อยนิ้ว ช่วยให้กดย้ำและหยุดเคลื่อนที่ได้เร็วกว่าคีย์บอร์ดทั่วไปอย่างเห็นได้ชัด นอกจากนี้ยังรองรับการกดแบบอนาล็อกเหมือนจอยเกม เช่น เดินช้าหรือเร็วตามแรงกดปุ่ม WASD

ทุกอย่างปรับได้ผ่านโปรแกรม Wootility บนเว็บ ทั้ง Snappy Tappy, Dynamic Keystroke และ Mod Tap บันทึกได้ 4 โปรไฟล์ในตัวคีย์บอร์ด พร้อมการรับประกันนานถึง 4 ปี', ARRAY['สวิตช์ Hall Effect แบบอนาล็อก วัดระยะกดได้ทุกปุ่ม', 'ปรับจุดทำงานได้ 0.1 – 4.0 มม. ละเอียดทีละ 0.1 มม.', 'Rapid Trigger ต้นตำรับจาก Wooting', 'Snappy Tappy (SOCD), Dynamic Keystroke และ Mod Tap', 'ใช้งานแบบจอยอนาล็อกได้ เช่น เดินช้า-เร็วตามแรงกด', 'รับประกัน 4 ปี (ไม่รวม LED)']::text[], '[{"label":"เลย์เอาต์","value":"60%"},{"label":"สวิตช์","value":"Lekker L60 Hall Effect (อนาล็อก)"},{"label":"จุดทำงาน","value":"0.1 – 4.0 มม. (ปรับทีละ 0.1 มม.)"},{"label":"Rapid Trigger","value":"รองรับ"},{"label":"การเชื่อมต่อ","value":"มีสาย USB-C (สายถัก 2 ม.)"},{"label":"วัสดุ","value":"เคส ABS, เพลตเหล็ก"},{"label":"น้ำหนัก","value":"605 กรัม"},{"label":"ขนาด","value":"30.2 × 11.6 × 3.8 ซม. (มุมเอียง 6 องศา)"}]'::jsonb FROM "categories" WHERE "category_name" = 'Keyboard' ON CONFLICT ("sku") DO NOTHING;
INSERT INTO "products" ("category_id", "sku", "product_name", "description", "price", "stock_quantity", "image_url", "details", "highlights", "specs") SELECT "category_id", 'KB-002', 'Keychron Q1 Pro', 'คีย์บอร์ด 75% บอดี้อะลูมิเนียม Hot-swap เชื่อมต่อไร้สาย Bluetooth', 6590, 15, '/products/kb-002.jpg', 'Keychron Q1 Pro คือคีย์บอร์ดคัสตอมขนาด 75% ที่มาพร้อมบอดี้อะลูมิเนียม CNC ทั้งชิ้น ให้ความรู้สึกหนักแน่นระดับพรีเมียม ภายในใช้โครงสร้าง double-gasket ที่ช่วยลดเสียงสะท้อนและทำให้การพิมพ์นุ่มนวล พร้อมปุ่มหมุน (knob) อะลูมิเนียมที่ตั้งค่าได้

ใช้งานได้ทั้งแบบไร้สายผ่าน Bluetooth 5.1 เชื่อมได้สูงสุด 3 อุปกรณ์ และแบบมีสาย USB-C รองรับทั้ง Mac และ Windows แบตเตอรี่ 4,000 mAh ใช้งานได้สูงสุด 300 ชั่วโมงเมื่อปิดไฟ

รองรับ QMK/VIA ปรับแต่งทุกปุ่มได้ผ่าน Keychron Launcher และเป็นแบบ hot-swap เปลี่ยนสวิตช์ MX ได้ทั้ง 3 ขาและ 5 ขาโดยไม่ต้องบัดกรี มาพร้อมคีย์แคป KSA double-shot PBT และไฟ RGB แบบ south-facing', ARRAY['บอดี้อะลูมิเนียม CNC ทั้งชิ้น', 'โครงสร้าง double-gasket ลดเสียงสะท้อน พิมพ์นุ่ม', 'รองรับ QMK/VIA ปรับแต่งได้ทุกปุ่ม', 'Hot-swap เปลี่ยนสวิตช์ MX ได้โดยไม่ต้องบัดกรี', 'Bluetooth 5.1 เชื่อมได้ 3 อุปกรณ์ + มีสาย USB-C', 'ปุ่มหมุนอะลูมิเนียมตั้งค่าได้']::text[], '[{"label":"เลย์เอาต์","value":"75% พร้อมปุ่มหมุน"},{"label":"การเชื่อมต่อ","value":"Bluetooth 5.1 (3 อุปกรณ์) / USB-C"},{"label":"Polling rate","value":"1,000 Hz (มีสาย) / 90 Hz (ไร้สาย)"},{"label":"แบตเตอรี่","value":"4,000 mAh สูงสุด 300 ชม. (ปิดไฟ)"},{"label":"บอดี้","value":"อะลูมิเนียม 6063 CNC"},{"label":"เพลต / การติดตั้ง","value":"เพลต PC, double-gasket"},{"label":"สวิตช์","value":"Keychron K Pro, hot-swap 3/5 ขา"},{"label":"คีย์แคป","value":"KSA double-shot PBT"},{"label":"ไฟ","value":"RGB แบบ south-facing"},{"label":"น้ำหนัก","value":"ประมาณ 1,736 กรัม"}]'::jsonb FROM "categories" WHERE "category_name" = 'Keyboard' ON CONFLICT ("sku") DO NOTHING;
INSERT INTO "products" ("category_id", "sku", "product_name", "description", "price", "stock_quantity", "image_url", "details", "highlights", "specs") SELECT "category_id", 'KB-003', 'Razer Huntsman V3 Pro TKL', 'สวิตช์ Analog Optical ปรับจุด actuation ได้ พร้อมที่พักข้อมือ', 7990, 8, '/products/kb-003.jpg', 'Razer Huntsman V3 Pro TKL คือคีย์บอร์ดเกมมิ่งขนาด tenkeyless ที่ออกแบบมาเพื่อการแข่งขัน ใช้สวิตช์ Razer Analog Optical Gen-2 ที่ปรับจุดทำงานได้ตั้งแต่ 0.1 ถึง 4.0 มม. และตั้งค่าได้แม้กระทั่งการทำงานสองจังหวะในปุ่มเดียว (dual-step actuation)

รองรับทั้ง Rapid Trigger ที่รีเซ็ตปุ่มได้เร็วสุด 0.1 มม. และ Snap Tap ที่ให้ความสำคัญกับปุ่มทิศทางที่กดล่าสุด ช่วยให้การเคลื่อนที่แบบ counter-strafe เร็วและแม่นยำขึ้น ปรับค่าได้ทันทีจากตัวคีย์บอร์ดโดยดูผลผ่านแถบไฟ LED

ตัวเครื่องด้านบนเป็นอะลูมิเนียมแบบแปรง คีย์แคป doubleshot PBT พื้นผิวสาก และมีที่พักข้อมือหนังแบบแม่เหล็กมาให้ พร้อมปุ่มหมุนมัลติฟังก์ชันและปุ่มมีเดีย', ARRAY['Razer Snap Tap และ Rapid Trigger', 'ปรับจุดทำงาน 0.1 – 4.0 มม. พร้อม dual-step actuation', 'ปรับค่าได้ทันทีจากตัวคีย์บอร์ดผ่านแถบไฟ LED', 'ปุ่มหมุนมัลติฟังก์ชันและปุ่มมีเดียเฉพาะ', 'ท็อปอะลูมิเนียมแบบแปรง คีย์แคป doubleshot PBT', 'สวิตช์ทนทาน 100 ล้านครั้ง']::text[], '[{"label":"ขนาด","value":"Tenkeyless (TKL)"},{"label":"สวิตช์","value":"Razer Analog Optical Gen-2"},{"label":"จุดทำงาน","value":"0.1 – 4.0 มม."},{"label":"Rapid Trigger","value":"รองรับ (รีเซ็ตได้ต่ำสุด 0.1 มม.)"},{"label":"แรงกด","value":"40 G"},{"label":"Polling rate","value":"1,000 Hz"},{"label":"การเชื่อมต่อ","value":"มีสาย USB-C ถอดได้"},{"label":"คีย์แคป","value":"Doubleshot PBT"},{"label":"ท็อปเคส","value":"อะลูมิเนียม 5052 แบบแปรง"},{"label":"ที่พักข้อมือ","value":"หนังเทียมแบบแม่เหล็ก"},{"label":"ไฟ","value":"Razer Chroma RGB"}]'::jsonb FROM "categories" WHERE "category_name" = 'Keyboard' ON CONFLICT ("sku") DO NOTHING;
INSERT INTO "products" ("category_id", "sku", "product_name", "description", "price", "stock_quantity", "image_url", "details", "highlights", "specs") SELECT "category_id", 'KB-004', 'Logitech G715', 'คีย์บอร์ดไร้สาย TKL ไฟ RGB ดีไซน์น่ารัก พร้อมที่พักข้อมือแบบคลาวด์', 5490, 12, '/products/kb-004.jpg', 'Logitech G715 คือคีย์บอร์ดไร้สายขนาด TKL จากคอลเลกชัน Aurora ที่เน้นดีไซน์น่ารักสดใส มาพร้อมที่พักข้อมือทรงก้อนเมฆที่นุ่มสบาย ช่วยให้เล่นเกมหรือพิมพ์งานได้นานโดยไม่เมื่อยข้อมือ

เชื่อมต่อได้ทั้ง LIGHTSPEED ไร้สายความหน่วงต่ำ Bluetooth และสาย USB-C สลับได้ด้วยปุ่มเดียว และยังใช้ตัวรับสัญญาณ LIGHTSPEED ร่วมกับเมาส์ G705 ได้ แบตเตอรี่ใช้งานได้สูงสุด 30 ชั่วโมงแม้เปิดไฟเต็มที่

ไฟ LIGHTSYNC RGB แยกทุกปุ่มพร้อมไฟรอบตัวเครื่อง 16 ดวง มีเอฟเฟกต์ Play Mood ให้เลือก 4 แบบ เลือกสวิตช์ GX ได้ทั้งแบบ Tactile, Linear และ Clicky พร้อมปุ่มมีเดียและลูกกลิ้งปรับเสียง', ARRAY['ดีไซน์ Aurora พร้อมที่พักข้อมือทรงก้อนเมฆ', 'ไร้สาย LIGHTSPEED + Bluetooth สลับได้ด้วยปุ่มเดียว', 'ใช้ตัวรับสัญญาณร่วมกับเมาส์ G705 ได้', 'ไฟ LIGHTSYNC RGB ทุกปุ่ม + ไฟรอบตัวเครื่อง', 'ปุ่มมีเดียพร้อมลูกกลิ้งปรับเสียง', 'แบตเตอรี่สูงสุด 30 ชั่วโมง']::text[], '[{"label":"เลย์เอาต์","value":"TKL 87 ปุ่ม"},{"label":"สวิตช์","value":"GX Mechanical (Tactile / Linear / Clicky)"},{"label":"การเชื่อมต่อ","value":"LIGHTSPEED / Bluetooth / USB-C"},{"label":"แบตเตอรี่","value":"สูงสุด 30 ชั่วโมง (ไฟสว่างสุด)"},{"label":"คีย์แคป","value":"Double-shot PBT"},{"label":"ไฟ","value":"LIGHTSYNC RGB ทุกปุ่ม + ไฟรอบตัวเครื่อง 16 ดวง"},{"label":"น้ำหนัก","value":"976 กรัม"},{"label":"ขนาด","value":"370.6 × 157 × 37.2 มม."},{"label":"รับประกัน","value":"2 ปี"}]'::jsonb FROM "categories" WHERE "category_name" = 'Keyboard' ON CONFLICT ("sku") DO NOTHING;
INSERT INTO "products" ("category_id", "sku", "product_name", "description", "price", "stock_quantity", "image_url", "details", "highlights", "specs") SELECT "category_id", 'HS-001', 'HyperX Cloud III', 'หูฟังเกมมิ่งใส่สบาย ไมค์ตัดเสียงรบกวน รองรับ DTS Spatial Audio', 3290, 30, '/products/hs-001.jpg', 'HyperX Cloud III คือวิวัฒนาการล่าสุดของหูฟังในตำนานอย่าง Cloud II ที่ขึ้นชื่อเรื่องความสบาย ยังคงใช้ฟองน้ำ memory foam และหนังเทียมพรีเมียมซิกเนเจอร์ของ HyperX สวมใส่ได้ทั้งวันโดยไม่เจ็บหู พร้อมโครงอะลูมิเนียมที่แข็งแรงแต่ยืดหยุ่น

ไดรเวอร์ขนาด 53 มม. ถูกออกแบบใหม่และวางเอียงให้เสียงเดินทางเข้าหูได้เป็นธรรมชาติ ตอบสนองความถี่กว้าง 10 Hz – 21 kHz ได้ยินทั้งเสียงฝีเท้าและรายละเอียดเล็กๆ ในเกมชัดเจน

ไมโครโฟน 10 มม. ถอดได้ ตัดเสียงรบกวน มีตัวกรองตาข่ายภายในและไฟแสดงสถานะปิดไมค์ เชื่อมต่อได้ทั้งแจ็ค 3.5 มม. USB-A และ USB-C ใช้ได้กับ PC, PS5, Xbox, Nintendo Switch และมือถือ', ARRAY['พัฒนาต่อจาก Cloud II พร้อม memory foam ซิกเนเจอร์ของ HyperX', 'ไดรเวอร์ 53 มม. ออกแบบใหม่แบบวางเอียง', 'ไมค์ 10 มม. ตัดเสียงรบกวน พร้อมไฟแสดงสถานะปิดไมค์', 'โครงอะลูมิเนียมทนทาน', 'ปุ่มปรับเสียงและปิดไมค์บนตัวหูฟัง', 'เชื่อมต่อได้ทั้ง 3.5 มม. USB-A และ USB-C']::text[], '[{"label":"ไดรเวอร์","value":"Dynamic 53 มม. แม่เหล็กนีโอดิเมียม"},{"label":"รูปแบบ","value":"ครอบหู แบบปิด"},{"label":"ตอบสนองความถี่","value":"10 Hz – 21 kHz"},{"label":"อิมพีแดนซ์","value":"64 Ω"},{"label":"ไมโครโฟน","value":"Condenser 10 มม. ถอดได้ ตัดเสียงรบกวน"},{"label":"การเชื่อมต่อ","value":"3.5 มม. / USB-A / USB-C"},{"label":"โครงสร้าง","value":"อะลูมิเนียม"},{"label":"น้ำหนัก","value":"308 กรัม (320 กรัม รวมไมค์)"},{"label":"รองรับ","value":"PC, PS5, PS4, Xbox, Switch, Mac, มือถือ"}]'::jsonb FROM "categories" WHERE "category_name" = 'Headset' ON CONFLICT ("sku") DO NOTHING;
INSERT INTO "products" ("category_id", "sku", "product_name", "description", "price", "stock_quantity", "image_url", "details", "highlights", "specs") SELECT "category_id", 'HS-002', 'SteelSeries Arctis Nova Pro', 'หูฟังระดับไฮเอนด์พร้อม GameDAC Gen 2 และเสียงระดับ Hi-Res', 11900, 5, '/products/hs-002.jpg', 'SteelSeries Arctis Nova Pro คือหูฟังเกมมิ่งระดับไฮเอนด์ที่มาพร้อม GameDAC Gen 2 ตัวถอดรหัสเสียงแยกที่ใช้ชิป ESS Sabre Quad-DAC ให้เสียงระดับ Hi-Res 96 kHz / 24-bit พร้อมหน้าจอและปุ่มหมุนสำหรับปรับเสียงได้ทันทีระหว่างเล่น

จุดเด่นคือ Multi-System Connect เสียบเครื่องเล่นได้สองเครื่องพร้อมกัน เช่น PC และ PS5 แล้วสลับได้ด้วยปุ่มเดียว เมื่อใช้ร่วมกับซอฟต์แวร์ SteelSeries Sonar จะได้ Parametric EQ ระดับมืออาชีพและเสียง 360° Spatial Audio

ไมโครโฟน ClearCast Gen 2 แบบ bidirectional ตัดเสียงรบกวนด้วย AI และเก็บซ่อนเข้าไปในตัวหูฟังได้เมื่อไม่ใช้งาน ครอบหูปรับได้หลายแบบ พร้อมแผ่นปิดด้านข้างแบบแม่เหล็กที่เปลี่ยนลายได้', ARRAY['GameDAC Gen 2 ชิป ESS Sabre Quad-DAC เสียง Hi-Res 96 kHz/24-bit', 'Multi-System Connect ต่อได้ 2 เครื่อง สลับด้วยปุ่มเดียว', 'Parametric EQ ระดับมืออาชีพผ่าน SteelSeries Sonar', 'ไมค์ ClearCast Gen 2 ตัดเสียงรบกวนด้วย AI เก็บซ่อนได้', 'ChatMix ปรับสมดุลเสียงเกมกับเสียงแชท', 'แผ่นปิดด้านข้างแบบแม่เหล็ก เปลี่ยนลายได้']::text[], '[{"label":"ไดรเวอร์","value":"Neodymium 40 มม. (Premium High Fidelity)"},{"label":"ตอบสนองความถี่","value":"10 – 40,000 Hz"},{"label":"ความไว / อิมพีแดนซ์","value":"93 dBSPL / 38 Ω"},{"label":"ไมโครโฟน","value":"ClearCast Gen 2 แบบเก็บได้, bidirectional"},{"label":"GameDAC","value":"Gen 2, ESS Sabre 9218PQ40, 96 kHz / 24-bit"},{"label":"การเชื่อมต่อ","value":"มีสาย ผ่าน GameDAC (USB-C × 2, line-in, line-out)"},{"label":"Spatial Audio","value":"360° ผ่าน SteelSeries Sonar / Tempest 3D (PS5)"},{"label":"มาตรฐาน","value":"Hi-Res Audio"}]'::jsonb FROM "categories" WHERE "category_name" = 'Headset' ON CONFLICT ("sku") DO NOTHING;
INSERT INTO "products" ("category_id", "sku", "product_name", "description", "price", "stock_quantity", "image_url", "details", "highlights", "specs") SELECT "category_id", 'HS-003', 'Razer BlackShark V2 Pro', 'หูฟังไร้สายสำหรับ eSports ไดรเวอร์ TriForce Titanium 50mm', 6990, 14, '/products/hs-003.jpg', 'Razer BlackShark V2 Pro คือหูฟังไร้สายที่ออกแบบมาเพื่อการแข่งขันอีสปอร์ตโดยเฉพาะ ใช้ไดรเวอร์ Razer TriForce Titanium ขนาด 50 มม. ที่แยกการปรับจูนเสียงสูง กลาง และต่ำ ให้เสียงคมชัด ได้ยินทิศทางเสียงฝีเท้าชัดเจน พร้อมโปรไฟล์เสียงสำหรับเกม FPS ที่ปรับจูนร่วมกับโปรเพลเยอร์

ไมโครโฟน Razer HyperClear Super Wideband แบบถอดได้ ให้เสียงพูดคมชัดระดับสูง เหมาะกับการคุยกับทีมและสตรีม เชื่อมต่อได้ทั้ง HyperSpeed Wireless 2.4 GHz และ Bluetooth 5.2 ใช้งานได้สองช่องทางพร้อมกัน

แบตเตอรี่ใช้งานได้นานสูงสุด 70 ชั่วโมง รองรับ THX Spatial Audio และมีโครงคาดศีรษะเสริมเหล็กกับฟองน้ำ memory foam ที่ช่วยลดแรงกด สวมใส่สบายตลอดการแข่งขัน', ARRAY['ไมค์ HyperClear Super Wideband ถอดได้ เสียงคมชัดระดับสูง', 'ไดรเวอร์ TriForce Titanium 50 มม.', 'โปรไฟล์เสียง FPS ปรับจูนร่วมกับโปรเพลเยอร์', 'ไร้สาย HyperSpeed 2.4 GHz + Bluetooth 5.2', 'แบตเตอรี่สูงสุด 70 ชั่วโมง', 'โครงเสริมเหล็กและ memory foam ลดแรงกด']::text[], '[{"label":"ไดรเวอร์","value":"Razer TriForce Titanium 50 มม."},{"label":"ตอบสนองความถี่","value":"12 Hz – 28 kHz"},{"label":"อิมพีแดนซ์","value":"32 Ω"},{"label":"การเชื่อมต่อ","value":"HyperSpeed Wireless 2.4 GHz + Bluetooth 5.2"},{"label":"แบตเตอรี่","value":"สูงสุด 70 ชั่วโมง"},{"label":"ไมโครโฟน","value":"HyperClear Super Wideband ถอดได้"},{"label":"Spatial Audio","value":"THX Spatial Audio"},{"label":"น้ำหนัก","value":"320 กรัม"},{"label":"รองรับ","value":"PC, PlayStation, มือถือ"}]'::jsonb FROM "categories" WHERE "category_name" = 'Headset' ON CONFLICT ("sku") DO NOTHING;
INSERT INTO "products" ("category_id", "sku", "product_name", "description", "price", "stock_quantity", "image_url", "details", "highlights", "specs") SELECT "category_id", 'MN-001', 'ASUS ROG Swift PG27AQDM', 'จอ OLED 27 นิ้ว 1440p 240Hz ความเร็วตอบสนอง 0.03ms', 32900, 4, '/products/mn-001.jpg', 'ASUS ROG Swift OLED PG27AQDM คือจอเกมมิ่ง OLED ขนาด 27 นิ้ว (26.5 นิ้วจริง) ความละเอียด QHD 2560 × 1440 รีเฟรชเรต 240 Hz และเวลาตอบสนองเพียง 0.03 ms ให้ภาพเคลื่อนไหวที่คมชัดไร้เงาเบลอ พร้อมคอนทราสต์ 1,500,000:1 ที่ให้สีดำสนิทแบบที่มีเฉพาะจอ OLED

ASUS ใส่ฮีตซิงก์แบบพิเศษเพื่อช่วยลดความเสี่ยงการเกิดภาพค้าง (burn-in) และรับประกัน 2 ปีรวมปัญหา burn-in ด้วย มาพร้อมฟีเจอร์ OLED Anti-Flicker และ Uniform Brightness ที่ช่วยให้ความสว่างสม่ำเสมอ

หน้าจอเคลือบด้านลดแสงสะท้อน ครอบคลุมสี DCI-P3 99% แบบ 10-bit รองรับ HDR10 ความสว่างสูงสุด 1,000 nits และรองรับทั้ง G-SYNC Compatible และ FreeSync Premium ขาตั้งปรับได้ครบทุกทิศทาง', ARRAY['OLED 240 Hz ตอบสนอง 0.03 ms ภาพคมไร้เงาเบลอ', 'ฮีตซิงก์พิเศษช่วยลดความเสี่ยง burn-in', 'รับประกัน 2 ปี รวมปัญหา burn-in', 'OLED Anti-Flicker และ Uniform Brightness', 'หน้าจอเคลือบด้าน ลดแสงสะท้อน', 'ไฟ Aura RGB และช่องยึดขาตั้งกล้อง 1/4 นิ้ว']::text[], '[{"label":"จอภาพ","value":"WOLED 26.5 นิ้ว เคลือบด้าน"},{"label":"ความละเอียด","value":"2560 × 1440 (QHD)"},{"label":"รีเฟรชเรต","value":"240 Hz"},{"label":"เวลาตอบสนอง","value":"0.03 ms (GtG)"},{"label":"HDR","value":"HDR10, สว่างสูงสุด 1,000 nits"},{"label":"สี","value":"DCI-P3 99%, 10-bit"},{"label":"คอนทราสต์","value":"1,500,000:1"},{"label":"Adaptive Sync","value":"FreeSync Premium / G-SYNC Compatible"},{"label":"พอร์ต","value":"DisplayPort 1.4 DSC, HDMI 2.0 × 2, USB 3.2 × 2, แจ็คหูฟัง"},{"label":"ขาตั้ง","value":"ปรับเอียง หมุน แนวตั้ง และความสูง 110 มม., VESA 100"},{"label":"รับประกัน","value":"2 ปี (รวม burn-in)"}]'::jsonb FROM "categories" WHERE "category_name" = 'Monitor' ON CONFLICT ("sku") DO NOTHING;
INSERT INTO "products" ("category_id", "sku", "product_name", "description", "price", "stock_quantity", "image_url", "details", "highlights", "specs") SELECT "category_id", 'MN-002', 'BenQ ZOWIE XL2546K', 'จอ TN 24.5 นิ้ว 240Hz เทคโนโลยี DyAc+ สำหรับเกม FPS', 16900, 7, '/products/mn-002.jpg', 'BenQ ZOWIE XL2546K คือจอเกมมิ่งขนาด 24.5 นิ้ว ที่ออกแบบมาเพื่อนักกีฬาอีสปอร์ตสาย FPS โดยเฉพาะ ใช้แผง TN ตอบสนองเร็ว ความละเอียด Full HD รีเฟรชเรต 240 Hz และเป็นจอที่พบเห็นได้บ่อยในทัวร์นาเมนต์ระดับโลก

หัวใจสำคัญคือเทคโนโลยี DyAc+ ที่ช่วยลดภาพเบลอขณะเคลื่อนไหว ทำให้มองเห็นเป้าหมายชัดขึ้นเวลายิงสเปรย์หรือหันกล้องเร็วๆ ร่วมกับ Black eQualizer ที่ช่วยให้มองเห็นศัตรูในที่มืด และ Color Vibrance ที่ปรับความสดของสีได้

มาพร้อมอุปกรณ์ครบชุด ทั้ง S Switch สำหรับสลับโหมดได้รวดเร็ว บังตาด้านข้างที่ช่วยลดสิ่งรบกวน และฐานขนาดเล็กที่ให้พื้นที่วางเมาส์มากขึ้น ขาตั้งปรับความสูงได้ 155 มม.', ARRAY['DyAc+ ลดภาพเบลอขณะเคลื่อนไหว เห็นเป้าชัดเวลายิงสเปรย์', 'Black eQualizer และ Color Vibrance ช่วยมองเห็นศัตรู', 'S Switch สลับโหมดภาพได้รวดเร็ว', 'บังตาด้านข้าง ลดสิ่งรบกวนสายตา', 'ฐานเล็ก เพิ่มพื้นที่วางเมาส์', 'รองรับ 120 Hz บน PS5 / Xbox Series X']::text[], '[{"label":"จอภาพ","value":"TN 24.5 นิ้ว"},{"label":"ความละเอียด","value":"1920 × 1080 (Full HD)"},{"label":"รีเฟรชเรต","value":"240 Hz (PC), 120 Hz (PS5 / Xbox Series X)"},{"label":"ความสว่าง","value":"320 nits"},{"label":"คอนทราสต์","value":"1000:1"},{"label":"ลดภาพเบลอ","value":"DyAc+"},{"label":"พอร์ต","value":"HDMI 2.0 × 3, DisplayPort 1.2, แจ็คหูฟัง"},{"label":"ขาตั้ง","value":"เอียง -5 ถึง 23°, หมุน 45°, ปรับสูง 155 มม., VESA 100"},{"label":"น้ำหนัก","value":"6.2 กก."},{"label":"ในกล่อง","value":"S Switch, บังตา, สาย DP, ผ้าคลุมกันฝุ่น"}]'::jsonb FROM "categories" WHERE "category_name" = 'Monitor' ON CONFLICT ("sku") DO NOTHING;
INSERT INTO "products" ("category_id", "sku", "product_name", "description", "price", "stock_quantity", "image_url", "details", "highlights", "specs") SELECT "category_id", 'MN-003', 'LG UltraGear 27GR95QE', 'จอ OLED 27 นิ้ว 240Hz สีสดคมชัด รองรับ G-Sync', 29900, 6, '/products/mn-003.jpg', 'LG UltraGear 27GR95QE คือจอเกมมิ่ง OLED ขนาด 27 นิ้ว (26.5 นิ้วจริง) ความละเอียด QHD รีเฟรชเรต 240 Hz ตอบสนองเพียง 0.03 ms ให้ภาพที่ลื่นไหลและคมชัด ทุกพิกเซลสร้างแสงเอง จึงได้สีดำที่ดำสนิทและคอนทราสต์สูงถึง 1,500,000:1

จอผ่านการคาลิเบรตสีจากโรงงานและรองรับ hardware calibration ครอบคลุมสี DCI-P3 98.5% รองรับ HDR10 ทั้งยังใช้ได้กับทั้ง G-SYNC Compatible และ FreeSync Premium เพื่อภาพที่ไม่ฉีกขาด

มีฟีเจอร์เกมมิ่งครบ ทั้ง Black Stabilizer, Crosshair และตัวนับ FPS พร้อมช่องหูฟัง 4-pole ที่รองรับ DTS Headphone:X ไฟ Hexagon RGB ด้านหลัง และรีโมตคอนโทรลสำหรับปรับการตั้งค่าได้สะดวก', ARRAY['OLED คอนทราสต์ 1,500,000:1 ตอบสนอง 0.03 ms', 'คาลิเบรตสีจากโรงงาน รองรับ hardware calibration', 'DTS Headphone:X ผ่านช่องหูฟัง 4-pole', 'ไฟ Hexagon RGB ด้านหลัง', 'มีรีโมตคอนโทรลในกล่อง', 'Black Stabilizer, Crosshair, ตัวนับ FPS']::text[], '[{"label":"จอภาพ","value":"OLED 26.5 นิ้ว"},{"label":"ความละเอียด","value":"2560 × 1440 (QHD)"},{"label":"รีเฟรชเรต","value":"240 Hz"},{"label":"เวลาตอบสนอง","value":"0.03 ms (GtG)"},{"label":"HDR","value":"HDR10"},{"label":"สี","value":"DCI-P3 98.5%, 1.07 พันล้านสี"},{"label":"คอนทราสต์","value":"1,500,000:1"},{"label":"Adaptive Sync","value":"G-SYNC Compatible / FreeSync Premium"},{"label":"พอร์ต","value":"DisplayPort 1.4, HDMI 2.1 × 2, USB 3.0 × 2, หูฟัง, Optical out"},{"label":"ขาตั้ง","value":"ปรับเอียง สูง หมุน และแนวตั้ง, VESA 100"}]'::jsonb FROM "categories" WHERE "category_name" = 'Monitor' ON CONFLICT ("sku") DO NOTHING;
INSERT INTO "products" ("category_id", "sku", "product_name", "description", "price", "stock_quantity", "image_url", "details", "highlights", "specs") SELECT "category_id", 'CH-001', 'Secretlab TITAN Evo', 'เก้าอี้เกมมิ่งพรีเมียม ปรับ lumbar support ในตัว วัสดุ NEO Hybrid Leatherette', 17900, 9, '/products/ch-001.jpg', 'Secretlab TITAN Evo คือเก้าอี้เกมมิ่งพรีเมียมที่ได้รับความนิยมจากทั้งเกมเมอร์และคนทำงาน จุดเด่นคือระบบรองรับหลังส่วนล่าง L-ADAPT แบบ 4 ทิศทางที่ติดตั้งมาในตัวเก้าอี้ ปรับได้ทั้งความสูงและความลึกให้พอดีกับกระดูกสันหลังของแต่ละคน

ที่วางแขนเป็นโครงโลหะทั้งชิ้นปรับได้ 4 ทิศทาง พร้อมระบบ CloudSwap เปลี่ยนแผ่นท็อปแบบแม่เหล็กได้ง่าย มาพร้อมหมอนรองศีรษะ memory foam ผสมเจลเย็นที่ยึดด้วยแม่เหล็ก ไม่ต้องใช้สายรัดให้เกะกะ

โครงเหล็ก โฟม cold-cure และกลไกเอนหลายระดับที่เอนได้สูงสุด 165 องศา ฐานอะลูมิเนียมพร้อมโช้คแก๊ส Class 4 ขนาด Regular นี้เหมาะกับผู้ใช้สูง 170–189 ซม. รับประกันยาวสูงสุด 5 ปี', ARRAY['ระบบรองรับหลังส่วนล่าง L-ADAPT 4 ทิศทางในตัว', 'ที่วางแขนโลหะ 4D พร้อมท็อปแม่เหล็ก CloudSwap', 'หมอนรองศีรษะ memory foam เจลเย็น ยึดด้วยแม่เหล็ก', 'เอนได้สูงสุด 165 องศา พร้อมกลไก multi-tilt', 'มีให้เลือก 3 ขนาด (S, R, XL)']::text[], '[{"label":"ขนาด","value":"Regular (R)"},{"label":"ความสูงผู้ใช้","value":"170 – 189 ซม."},{"label":"น้ำหนักผู้ใช้แนะนำ","value":"ไม่เกิน 100 กก."},{"label":"รับน้ำหนักสูงสุด","value":"130 กก."},{"label":"การเอน","value":"85 – 165 องศา"},{"label":"ที่วางแขน","value":"โลหะ 4D พร้อม CloudSwap"},{"label":"รองรับหลัง","value":"L-ADAPT 4 ทิศทางในตัว"},{"label":"วัสดุ","value":"โครงเหล็ก, โฟม cold-cure, NEO Hybrid Leatherette"},{"label":"ฐาน / โช้ค","value":"ฐานอะลูมิเนียม, โช้คแก๊ส Class 4"},{"label":"รับประกัน","value":"สูงสุด 5 ปี"}]'::jsonb FROM "categories" WHERE "category_name" = 'Chair' ON CONFLICT ("sku") DO NOTHING;
INSERT INTO "products" ("category_id", "sku", "product_name", "description", "price", "stock_quantity", "image_url", "details", "highlights", "specs") SELECT "category_id", 'CH-002', 'Anda Seat Kaiser 3', 'เก้าอี้เกมมิ่งไซซ์ใหญ่ ที่วางแขน 4D พนักพิงเอนได้ 155 องศา', 14900, 11, '/products/ch-002.jpg', 'Anda Seat Kaiser 3 คือเก้าอี้เกมมิ่งไซซ์ใหญ่ที่เน้นความแข็งแรงและการรองรับร่างกายอย่างเต็มที่ โครงสร้างเหล็ก 100% และโฟม cold-cure ความหนาแน่นสูง 65 กก./ลบ.ม. ให้ความนุ่มแน่นที่ไม่ยุบตัวง่าย ผ่านมาตรฐาน ANSI/BIFMA และ EN1335

ระบบรองรับหลังส่วนล่างแบบ 4 ทิศทางติดตั้งในตัว ปรับด้วยปุ่มหมุนทั้งสองข้าง หมอนรองศีรษะแม่เหล็กปรับตำแหน่งได้ในช่วง 20 ซม. และที่วางแขน 4D เปลี่ยนท็อปแม่เหล็ก MagSwap ได้ถึง 7 สี

เอนพนักพิงได้ 90–155 องศา พร้อมโหมดโยก 15 องศา ฐานอะลูมิเนียมแข็งแรงพร้อมล้อ PU ขนาด 65 มม. ขนาด L นี้เหมาะกับผู้ใช้สูง 150–190 ซม. น้ำหนักไม่เกิน 120 กก. รับประกัน 5 ปี', ARRAY['ระบบรองรับหลัง 4 ทิศทางในตัว ปรับด้วยปุ่มหมุนสองข้าง', 'หมอนรองศีรษะแม่เหล็ก ปรับได้ในช่วง 20 ซม.', 'ที่วางแขน 4D เปลี่ยนท็อปแม่เหล็กได้ 7 สี', 'เอนได้ 155 องศา พร้อมโหมดโยก 15 องศา', 'ผ่านมาตรฐาน ANSI/BIFMA, EN12520, EN1335']::text[], '[{"label":"ขนาด","value":"L"},{"label":"ความสูงผู้ใช้","value":"150 – 190 ซม."},{"label":"น้ำหนักผู้ใช้แนะนำ","value":"ไม่เกิน 120 กก."},{"label":"การเอน","value":"90 – 155 องศา + โยก 15 องศา"},{"label":"ที่วางแขน","value":"4D พร้อมท็อปแม่เหล็ก MagSwap"},{"label":"รองรับหลัง","value":"4 ทิศทางในตัว"},{"label":"วัสดุ","value":"โครงเหล็ก 100%, โฟม cold-cure 65 กก./ลบ.ม."},{"label":"ฐาน / โช้ค","value":"ฐานอะลูมิเนียม, ล้อ PU 65 มม., โช้คแก๊ส Class 4"},{"label":"ความสูงเบาะ","value":"44.5 – 51 ซม."},{"label":"น้ำหนักเก้าอี้","value":"30.05 กก."},{"label":"รับประกัน","value":"5 ปี"}]'::jsonb FROM "categories" WHERE "category_name" = 'Chair' ON CONFLICT ("sku") DO NOTHING;
INSERT INTO "products" ("category_id", "sku", "product_name", "description", "price", "stock_quantity", "image_url", "details", "highlights", "specs") SELECT "category_id", 'CT-001', 'Xbox Wireless Controller', 'จอยไร้สายใช้ได้ทั้ง Xbox และ PC เชื่อมต่อ Bluetooth', 2190, 35, '/products/ct-001.jpg', 'Xbox Wireless Controller คือจอยมาตรฐานของ Xbox รุ่นปัจจุบัน ที่ใช้งานได้ทั้งบน Xbox Series X|S, Xbox One, Windows และมือถือ ด้วยการเชื่อมต่อ Xbox Wireless สำหรับคอนโซล และ Bluetooth สำหรับ PC แท็บเล็ต iOS และ Android สลับอุปกรณ์ได้รวดเร็ว

รุ่นนี้เพิ่มปุ่ม Share สำหรับจับภาพหน้าจอและบันทึกวิดีโอได้ทันที พร้อม D-pad แบบไฮบริดที่กดแนวทแยงได้แม่นยำขึ้น และพื้นผิวกันลื่นบนทริกเกอร์ บัมเปอร์ และด้านหลังตัวจอย จับได้มั่นคงตลอดการเล่น

ใช้ถ่าน AA ได้นานสูงสุด 40 ชั่วโมง มีช่องเสียบหูฟัง 3.5 มม. และตั้งค่าปุ่มใหม่ได้ผ่านแอป Xbox Accessories', ARRAY['ปุ่ม Share จับภาพหน้าจอและบันทึกวิดีโอ', 'D-pad แบบไฮบริด', 'พื้นผิวกันลื่นบนทริกเกอร์ บัมเปอร์ และด้านหลัง', 'เชื่อมต่อและสลับได้ทั้ง Xbox, PC และมือถือ', 'ตั้งค่าปุ่มใหม่ได้ผ่านแอป Xbox Accessories']::text[], '[{"label":"รองรับ","value":"Xbox Series X|S, Xbox One, Windows 10/11, Android, iOS"},{"label":"การเชื่อมต่อ","value":"Xbox Wireless / Bluetooth / USB-C"},{"label":"แบตเตอรี่","value":"ถ่าน AA ใช้งานได้สูงสุด 40 ชั่วโมง"},{"label":"เสียง","value":"ช่องหูฟัง 3.5 มม."},{"label":"D-pad","value":"แบบไฮบริด"},{"label":"การจับ","value":"พื้นผิวกันลื่นบนทริกเกอร์ บัมเปอร์ และด้านหลัง"},{"label":"ตั้งค่าปุ่ม","value":"ผ่านแอป Xbox Accessories"}]'::jsonb FROM "categories" WHERE "category_name" = 'Controller' ON CONFLICT ("sku") DO NOTHING;
INSERT INTO "products" ("category_id", "sku", "product_name", "description", "price", "stock_quantity", "image_url", "details", "highlights", "specs") SELECT "category_id", 'CT-002', 'PlayStation DualSense Edge', 'จอยโปรสำหรับ PS5 ปุ่มหลังปรับแต่งได้ เปลี่ยนก้านอนาล็อกได้', 7590, 8, '/products/ct-002.jpg', 'PlayStation DualSense Edge คือจอยระดับโปรสำหรับ PS5 ที่ให้คุณปรับแต่งได้แทบทุกส่วน มีปุ่มหลังแบบเปลี่ยนได้สองแบบทั้งทรงโดมและทรงคันโยก และตัวล็อกระยะทริกเกอร์ L2/R2 ที่ช่วยให้กดยิงได้เร็วขึ้นในเกมแอ็กชัน

ก้านอนาล็อกเปลี่ยนได้ทั้งโมดูล (ขายแยก) หากเกิดปัญหาก็เปลี่ยนเองได้ พร้อมหัวก้านให้เลือก 3 แบบ ตั้งค่าโปรไฟล์การควบคุมได้หลายชุด และสลับได้ทันทีด้วยปุ่ม Fn รวมถึงปรับความไวของก้าน dead zone และความแรงของการสั่นได้ตามต้องการ

ยังคงมีฟีเจอร์ของ DualSense ครบทั้ง haptic feedback, adaptive triggers และไมโครโฟนในตัว มาพร้อมสาย USB-C ถัก 2.8 เมตรแบบล็อกหัวได้ และกระเป๋าเก็บจอยที่ชาร์จได้ในตัว', ARRAY['ปุ่มหลังเปลี่ยนได้ 2 แบบ (โดม / คันโยก)', 'ตัวล็อกระยะทริกเกอร์ L2/R2', 'เปลี่ยนโมดูลก้านอนาล็อกได้ พร้อมหัวก้าน 3 แบบ', 'สลับโปรไฟล์การควบคุมด้วยปุ่ม Fn', 'Haptic feedback และ adaptive triggers', 'มีกระเป๋าเก็บจอยที่ชาร์จได้ในตัว']::text[], '[{"label":"รองรับ","value":"PS5, PC (USB หรือ Bluetooth)"},{"label":"การเชื่อมต่อ","value":"Bluetooth / USB-C (สายถัก 2.8 ม. แบบล็อกหัว)"},{"label":"ปุ่มหลัง","value":"เปลี่ยนได้ 2 แบบ (โดม / คันโยก)"},{"label":"ทริกเกอร์","value":"ตัวล็อกระยะ L2/R2"},{"label":"ก้านอนาล็อก","value":"เปลี่ยนโมดูลได้ (ขายแยก), หัวก้าน 3 แบบ"},{"label":"แบตเตอรี่","value":"Li-ion 1,050 mAh"},{"label":"น้ำหนัก","value":"ประมาณ 325 กรัม"},{"label":"ฟีเจอร์ DualSense","value":"Haptic feedback, adaptive triggers, ไมค์ในตัว, motion"}]'::jsonb FROM "categories" WHERE "category_name" = 'Controller' ON CONFLICT ("sku") DO NOTHING;
INSERT INTO "products" ("category_id", "sku", "product_name", "description", "price", "stock_quantity", "image_url", "details", "highlights", "specs") SELECT "category_id", 'CT-003', '8BitDo Ultimate 2', 'จอยไร้สายก้าน Hall Effect พร้อมแท่นชาร์จ รองรับ PC และ Switch', 2290, 20, '/products/ct-003.jpg', '8BitDo Ultimate 2 Wireless คือจอยไร้สายที่อัดแน่นด้วยเทคโนโลยีระดับพรีเมียมในราคาที่เข้าถึงได้ ใช้ก้าน TMR ที่แม่นยำและทนทาน ไม่มีปัญหาก้านดริฟต์แบบก้านทั่วไป และทริกเกอร์ Hall Effect ที่สลับได้ระหว่างโหมดกดแบบ linear และแบบ tactile

รองรับ polling rate 1,000 Hz ทั้งแบบไร้สาย 2.4G และแบบมีสาย พร้อมปุ่มเสริมทั้งบัมเปอร์ L4/R4 และปุ่มหลังแบบ Pro อีก 2 ปุ่ม ตั้งค่าได้ผ่านซอฟต์แวร์ Ultimate Software V2 และบันทึกได้ 3 โปรไฟล์

มาพร้อมแท่นชาร์จที่เชื่อมกับ PC ผ่าน USB เพื่อช่วยขยายสัญญาณ 2.4G ไฟ Fire Ring RGB รอบก้านอนาล็อก รองรับ motion control 6 แกน และการสั่น ใช้งานได้กับ Windows, SteamOS และอุปกรณ์ Android/Apple ผ่าน Bluetooth', ARRAY['ก้าน TMR แม่นยำและทนทาน', 'ทริกเกอร์ Hall Effect สลับโหมด linear / tactile', 'Polling rate 1,000 Hz ทั้ง 2.4G และมีสาย', 'ปุ่มเสริม L4/R4 และปุ่มหลัง Pro 2 ปุ่ม', 'แท่นชาร์จในกล่อง ช่วยขยายสัญญาณ 2.4G', 'ไฟ Fire Ring RGB รอบก้าน']::text[], '[{"label":"รองรับ","value":"Windows 10+, SteamOS, Android 13+, อุปกรณ์ Apple"},{"label":"การเชื่อมต่อ","value":"2.4G ไร้สาย / Bluetooth / มีสาย"},{"label":"Polling rate","value":"1,000 Hz (2.4G และมีสาย)"},{"label":"ก้านอนาล็อก","value":"TMR, ADC 12-bit"},{"label":"ทริกเกอร์","value":"Hall Effect สลับโหมด linear / tactile"},{"label":"ปุ่มเสริม","value":"L4/R4 และปุ่มหลัง Pro 2 ปุ่ม"},{"label":"ฟีเจอร์อื่น","value":"Motion 6 แกน, การสั่น, turbo, 3 โปรไฟล์"},{"label":"การชาร์จ","value":"แท่นชาร์จในกล่อง"}]'::jsonb FROM "categories" WHERE "category_name" = 'Controller' ON CONFLICT ("sku") DO NOTHING;
INSERT INTO "products" ("category_id", "sku", "product_name", "description", "price", "stock_quantity", "image_url", "details", "highlights", "specs") SELECT "category_id", 'CT-004', 'Razer Wolverine V3 Pro', 'จอยสำหรับ Xbox/PC ปุ่ม Mecha-Tactile และ Trigger Stop', 6990, 3, '/products/ct-004.jpg', 'Razer Wolverine V3 Pro คือจอยระดับโปรสำหรับ Xbox และ PC ที่ได้รับลิขสิทธิ์อย่างเป็นทางการจาก Xbox ออกแบบมาเพื่อการแข่งขัน ใช้ก้านอนาล็อก Hall Effect ที่ป้องกันปัญหาก้านดริฟต์ และทริกเกอร์ Razer Pro HyperTriggers ที่เลื่อนล็อกเป็นแบบคลิกเหมือนเมาส์ได้ ยิงได้เร็วทันใจ

มีปุ่มที่ตั้งค่าได้ถึง 6 ปุ่ม ทั้งปุ่มหลังแบบคลิกเมาส์ 4 ปุ่ม และบัมเปอร์สำหรับการจับแบบ claw grip อีก 2 ปุ่ม ช่วยให้ไม่ต้องละนิ้วโป้งออกจากก้านอนาล็อก ปุ่มหลักใช้ Razer Mecha-Tactile ที่ให้สัมผัสการกดชัดเจน

เชื่อมต่อไร้สายด้วย Razer HyperSpeed หรือแบบมีสาย เมื่อใช้โหมด Tournament บน PC แบบมีสายจะได้ polling rate สูงสุด 1,000 Hz แบตเตอรี่ใช้งานได้ประมาณ 20 ชั่วโมง พร้อมไฟ Razer Chroma RGB และกระเป๋าเก็บจอย', ARRAY['ได้รับลิขสิทธิ์อย่างเป็นทางการจาก Xbox', 'Razer Pro HyperTriggers ล็อกเป็นคลิกแบบเมาส์ได้', 'ก้านอนาล็อก Hall Effect ป้องกันก้านดริฟต์', 'ปุ่มตั้งค่าได้ 6 ปุ่ม (ปุ่มหลัง 4 + บัมเปอร์ claw grip 2)', 'ปรับแต่งผ่านแอป Razer Controller', 'มีกระเป๋าเก็บจอยและไฟ Razer Chroma RGB']::text[], '[{"label":"รองรับ","value":"Xbox Series X|S, Xbox, PC (Windows 11)"},{"label":"การเชื่อมต่อ","value":"Razer HyperSpeed 2.4 GHz / สาย USB-C 3 ม."},{"label":"Polling rate","value":"250 Hz (ไร้สาย / Xbox), 1,000 Hz (PC Tournament Mode)"},{"label":"ก้านอนาล็อก","value":"Hall Effect ป้องกันดริฟต์ เปลี่ยนหัวได้"},{"label":"ทริกเกอร์","value":"Hall Effect พร้อมตัวล็อกแบบคลิกเมาส์"},{"label":"ปุ่มเสริม","value":"ปุ่มหลัง 4 ปุ่ม + บัมเปอร์ claw grip 2 ปุ่ม"},{"label":"ปุ่มหลัก","value":"Razer Mecha-Tactile"},{"label":"แบตเตอรี่","value":"ประมาณ 20 ชั่วโมง"},{"label":"น้ำหนัก","value":"304 กรัม"},{"label":"ขนาด","value":"156.7 × 105.7 × 65 มม."}]'::jsonb FROM "categories" WHERE "category_name" = 'Controller' ON CONFLICT ("sku") DO NOTHING;

INSERT INTO "product_images" ("product_id", "image_url", "sort_order") SELECT "product_id", '/products/ms-001.jpg', 0 FROM "products" WHERE "sku" = 'MS-001';
INSERT INTO "product_images" ("product_id", "image_url", "sort_order") SELECT "product_id", '/products/ms-001-2.jpg', 1 FROM "products" WHERE "sku" = 'MS-001';
INSERT INTO "product_images" ("product_id", "image_url", "sort_order") SELECT "product_id", '/products/ms-001-3.jpg', 2 FROM "products" WHERE "sku" = 'MS-001';
INSERT INTO "product_images" ("product_id", "image_url", "sort_order") SELECT "product_id", '/products/ms-001-4.jpg', 3 FROM "products" WHERE "sku" = 'MS-001';
INSERT INTO "product_images" ("product_id", "image_url", "sort_order") SELECT "product_id", '/products/ms-002.jpg', 0 FROM "products" WHERE "sku" = 'MS-002';
INSERT INTO "product_images" ("product_id", "image_url", "sort_order") SELECT "product_id", '/products/ms-002-2.jpg', 1 FROM "products" WHERE "sku" = 'MS-002';
INSERT INTO "product_images" ("product_id", "image_url", "sort_order") SELECT "product_id", '/products/ms-002-3.jpg', 2 FROM "products" WHERE "sku" = 'MS-002';
INSERT INTO "product_images" ("product_id", "image_url", "sort_order") SELECT "product_id", '/products/ms-002-4.jpg', 3 FROM "products" WHERE "sku" = 'MS-002';
INSERT INTO "product_images" ("product_id", "image_url", "sort_order") SELECT "product_id", '/products/ms-003.jpg', 0 FROM "products" WHERE "sku" = 'MS-003';
INSERT INTO "product_images" ("product_id", "image_url", "sort_order") SELECT "product_id", '/products/ms-003-2.jpg', 1 FROM "products" WHERE "sku" = 'MS-003';
INSERT INTO "product_images" ("product_id", "image_url", "sort_order") SELECT "product_id", '/products/ms-003-3.jpg', 2 FROM "products" WHERE "sku" = 'MS-003';
INSERT INTO "product_images" ("product_id", "image_url", "sort_order") SELECT "product_id", '/products/ms-003-4.jpg', 3 FROM "products" WHERE "sku" = 'MS-003';
INSERT INTO "product_images" ("product_id", "image_url", "sort_order") SELECT "product_id", '/products/ms-004.jpg', 0 FROM "products" WHERE "sku" = 'MS-004';
INSERT INTO "product_images" ("product_id", "image_url", "sort_order") SELECT "product_id", '/products/ms-004-2.jpg', 1 FROM "products" WHERE "sku" = 'MS-004';
INSERT INTO "product_images" ("product_id", "image_url", "sort_order") SELECT "product_id", '/products/ms-004-3.jpg', 2 FROM "products" WHERE "sku" = 'MS-004';
INSERT INTO "product_images" ("product_id", "image_url", "sort_order") SELECT "product_id", '/products/ms-004-4.jpg', 3 FROM "products" WHERE "sku" = 'MS-004';
INSERT INTO "product_images" ("product_id", "image_url", "sort_order") SELECT "product_id", '/products/kb-001.jpg', 0 FROM "products" WHERE "sku" = 'KB-001';
INSERT INTO "product_images" ("product_id", "image_url", "sort_order") SELECT "product_id", '/products/kb-001-2.jpg', 1 FROM "products" WHERE "sku" = 'KB-001';
INSERT INTO "product_images" ("product_id", "image_url", "sort_order") SELECT "product_id", '/products/kb-001-3.jpg', 2 FROM "products" WHERE "sku" = 'KB-001';
INSERT INTO "product_images" ("product_id", "image_url", "sort_order") SELECT "product_id", '/products/kb-001-4.jpg', 3 FROM "products" WHERE "sku" = 'KB-001';
INSERT INTO "product_images" ("product_id", "image_url", "sort_order") SELECT "product_id", '/products/kb-002.jpg', 0 FROM "products" WHERE "sku" = 'KB-002';
INSERT INTO "product_images" ("product_id", "image_url", "sort_order") SELECT "product_id", '/products/kb-002-2.jpg', 1 FROM "products" WHERE "sku" = 'KB-002';
INSERT INTO "product_images" ("product_id", "image_url", "sort_order") SELECT "product_id", '/products/kb-002-3.jpg', 2 FROM "products" WHERE "sku" = 'KB-002';
INSERT INTO "product_images" ("product_id", "image_url", "sort_order") SELECT "product_id", '/products/kb-002-4.jpg', 3 FROM "products" WHERE "sku" = 'KB-002';
INSERT INTO "product_images" ("product_id", "image_url", "sort_order") SELECT "product_id", '/products/kb-003.jpg', 0 FROM "products" WHERE "sku" = 'KB-003';
INSERT INTO "product_images" ("product_id", "image_url", "sort_order") SELECT "product_id", '/products/kb-003-2.jpg', 1 FROM "products" WHERE "sku" = 'KB-003';
INSERT INTO "product_images" ("product_id", "image_url", "sort_order") SELECT "product_id", '/products/kb-003-3.jpg', 2 FROM "products" WHERE "sku" = 'KB-003';
INSERT INTO "product_images" ("product_id", "image_url", "sort_order") SELECT "product_id", '/products/kb-003-4.jpg', 3 FROM "products" WHERE "sku" = 'KB-003';
INSERT INTO "product_images" ("product_id", "image_url", "sort_order") SELECT "product_id", '/products/kb-004.jpg', 0 FROM "products" WHERE "sku" = 'KB-004';
INSERT INTO "product_images" ("product_id", "image_url", "sort_order") SELECT "product_id", '/products/kb-004-2.jpg', 1 FROM "products" WHERE "sku" = 'KB-004';
INSERT INTO "product_images" ("product_id", "image_url", "sort_order") SELECT "product_id", '/products/kb-004-3.jpg', 2 FROM "products" WHERE "sku" = 'KB-004';
INSERT INTO "product_images" ("product_id", "image_url", "sort_order") SELECT "product_id", '/products/kb-004-4.jpg', 3 FROM "products" WHERE "sku" = 'KB-004';
INSERT INTO "product_images" ("product_id", "image_url", "sort_order") SELECT "product_id", '/products/hs-001.jpg', 0 FROM "products" WHERE "sku" = 'HS-001';
INSERT INTO "product_images" ("product_id", "image_url", "sort_order") SELECT "product_id", '/products/hs-001-2.jpg', 1 FROM "products" WHERE "sku" = 'HS-001';
INSERT INTO "product_images" ("product_id", "image_url", "sort_order") SELECT "product_id", '/products/hs-001-3.jpg', 2 FROM "products" WHERE "sku" = 'HS-001';
INSERT INTO "product_images" ("product_id", "image_url", "sort_order") SELECT "product_id", '/products/hs-001-4.jpg', 3 FROM "products" WHERE "sku" = 'HS-001';
INSERT INTO "product_images" ("product_id", "image_url", "sort_order") SELECT "product_id", '/products/hs-002.jpg', 0 FROM "products" WHERE "sku" = 'HS-002';
INSERT INTO "product_images" ("product_id", "image_url", "sort_order") SELECT "product_id", '/products/hs-002-2.jpg', 1 FROM "products" WHERE "sku" = 'HS-002';
INSERT INTO "product_images" ("product_id", "image_url", "sort_order") SELECT "product_id", '/products/hs-002-3.jpg', 2 FROM "products" WHERE "sku" = 'HS-002';
INSERT INTO "product_images" ("product_id", "image_url", "sort_order") SELECT "product_id", '/products/hs-002-4.jpg', 3 FROM "products" WHERE "sku" = 'HS-002';
INSERT INTO "product_images" ("product_id", "image_url", "sort_order") SELECT "product_id", '/products/hs-003.jpg', 0 FROM "products" WHERE "sku" = 'HS-003';
INSERT INTO "product_images" ("product_id", "image_url", "sort_order") SELECT "product_id", '/products/hs-003-2.jpg', 1 FROM "products" WHERE "sku" = 'HS-003';
INSERT INTO "product_images" ("product_id", "image_url", "sort_order") SELECT "product_id", '/products/hs-003-3.jpg', 2 FROM "products" WHERE "sku" = 'HS-003';
INSERT INTO "product_images" ("product_id", "image_url", "sort_order") SELECT "product_id", '/products/mn-001.jpg', 0 FROM "products" WHERE "sku" = 'MN-001';
INSERT INTO "product_images" ("product_id", "image_url", "sort_order") SELECT "product_id", '/products/mn-001-2.jpg', 1 FROM "products" WHERE "sku" = 'MN-001';
INSERT INTO "product_images" ("product_id", "image_url", "sort_order") SELECT "product_id", '/products/mn-001-3.jpg', 2 FROM "products" WHERE "sku" = 'MN-001';
INSERT INTO "product_images" ("product_id", "image_url", "sort_order") SELECT "product_id", '/products/mn-001-4.jpg', 3 FROM "products" WHERE "sku" = 'MN-001';
INSERT INTO "product_images" ("product_id", "image_url", "sort_order") SELECT "product_id", '/products/mn-002.jpg', 0 FROM "products" WHERE "sku" = 'MN-002';
INSERT INTO "product_images" ("product_id", "image_url", "sort_order") SELECT "product_id", '/products/mn-002-2.jpg', 1 FROM "products" WHERE "sku" = 'MN-002';
INSERT INTO "product_images" ("product_id", "image_url", "sort_order") SELECT "product_id", '/products/mn-002-3.jpg', 2 FROM "products" WHERE "sku" = 'MN-002';
INSERT INTO "product_images" ("product_id", "image_url", "sort_order") SELECT "product_id", '/products/mn-002-4.jpg', 3 FROM "products" WHERE "sku" = 'MN-002';
INSERT INTO "product_images" ("product_id", "image_url", "sort_order") SELECT "product_id", '/products/mn-003.jpg', 0 FROM "products" WHERE "sku" = 'MN-003';
INSERT INTO "product_images" ("product_id", "image_url", "sort_order") SELECT "product_id", '/products/mn-003-2.jpg', 1 FROM "products" WHERE "sku" = 'MN-003';
INSERT INTO "product_images" ("product_id", "image_url", "sort_order") SELECT "product_id", '/products/mn-003-3.jpg', 2 FROM "products" WHERE "sku" = 'MN-003';
INSERT INTO "product_images" ("product_id", "image_url", "sort_order") SELECT "product_id", '/products/mn-003-4.jpg', 3 FROM "products" WHERE "sku" = 'MN-003';
INSERT INTO "product_images" ("product_id", "image_url", "sort_order") SELECT "product_id", '/products/ch-001.jpg', 0 FROM "products" WHERE "sku" = 'CH-001';
INSERT INTO "product_images" ("product_id", "image_url", "sort_order") SELECT "product_id", '/products/ch-001-2.jpg', 1 FROM "products" WHERE "sku" = 'CH-001';
INSERT INTO "product_images" ("product_id", "image_url", "sort_order") SELECT "product_id", '/products/ch-001-3.jpg', 2 FROM "products" WHERE "sku" = 'CH-001';
INSERT INTO "product_images" ("product_id", "image_url", "sort_order") SELECT "product_id", '/products/ch-001-4.jpg', 3 FROM "products" WHERE "sku" = 'CH-001';
INSERT INTO "product_images" ("product_id", "image_url", "sort_order") SELECT "product_id", '/products/ch-002.jpg', 0 FROM "products" WHERE "sku" = 'CH-002';
INSERT INTO "product_images" ("product_id", "image_url", "sort_order") SELECT "product_id", '/products/ch-002-2.jpg', 1 FROM "products" WHERE "sku" = 'CH-002';
INSERT INTO "product_images" ("product_id", "image_url", "sort_order") SELECT "product_id", '/products/ch-002-3.jpg', 2 FROM "products" WHERE "sku" = 'CH-002';
INSERT INTO "product_images" ("product_id", "image_url", "sort_order") SELECT "product_id", '/products/ch-002-4.jpg', 3 FROM "products" WHERE "sku" = 'CH-002';
INSERT INTO "product_images" ("product_id", "image_url", "sort_order") SELECT "product_id", '/products/ct-001.jpg', 0 FROM "products" WHERE "sku" = 'CT-001';
INSERT INTO "product_images" ("product_id", "image_url", "sort_order") SELECT "product_id", '/products/ct-001-2.jpg', 1 FROM "products" WHERE "sku" = 'CT-001';
INSERT INTO "product_images" ("product_id", "image_url", "sort_order") SELECT "product_id", '/products/ct-001-3.jpg', 2 FROM "products" WHERE "sku" = 'CT-001';
INSERT INTO "product_images" ("product_id", "image_url", "sort_order") SELECT "product_id", '/products/ct-001-4.jpg', 3 FROM "products" WHERE "sku" = 'CT-001';
INSERT INTO "product_images" ("product_id", "image_url", "sort_order") SELECT "product_id", '/products/ct-002.jpg', 0 FROM "products" WHERE "sku" = 'CT-002';
INSERT INTO "product_images" ("product_id", "image_url", "sort_order") SELECT "product_id", '/products/ct-002-2.jpg', 1 FROM "products" WHERE "sku" = 'CT-002';
INSERT INTO "product_images" ("product_id", "image_url", "sort_order") SELECT "product_id", '/products/ct-002-3.jpg', 2 FROM "products" WHERE "sku" = 'CT-002';
INSERT INTO "product_images" ("product_id", "image_url", "sort_order") SELECT "product_id", '/products/ct-002-4.jpg', 3 FROM "products" WHERE "sku" = 'CT-002';
INSERT INTO "product_images" ("product_id", "image_url", "sort_order") SELECT "product_id", '/products/ct-003.jpg', 0 FROM "products" WHERE "sku" = 'CT-003';
INSERT INTO "product_images" ("product_id", "image_url", "sort_order") SELECT "product_id", '/products/ct-003-2.jpg', 1 FROM "products" WHERE "sku" = 'CT-003';
INSERT INTO "product_images" ("product_id", "image_url", "sort_order") SELECT "product_id", '/products/ct-003-3.jpg', 2 FROM "products" WHERE "sku" = 'CT-003';
INSERT INTO "product_images" ("product_id", "image_url", "sort_order") SELECT "product_id", '/products/ct-003-4.jpg', 3 FROM "products" WHERE "sku" = 'CT-003';
INSERT INTO "product_images" ("product_id", "image_url", "sort_order") SELECT "product_id", '/products/ct-004.jpg', 0 FROM "products" WHERE "sku" = 'CT-004';
INSERT INTO "product_images" ("product_id", "image_url", "sort_order") SELECT "product_id", '/products/ct-004-2.jpg', 1 FROM "products" WHERE "sku" = 'CT-004';
INSERT INTO "product_images" ("product_id", "image_url", "sort_order") SELECT "product_id", '/products/ct-004-3.jpg', 2 FROM "products" WHERE "sku" = 'CT-004';
INSERT INTO "product_images" ("product_id", "image_url", "sort_order") SELECT "product_id", '/products/ct-004-4.jpg', 3 FROM "products" WHERE "sku" = 'CT-004';

-- ===== Lock down the Supabase REST API =====
ALTER TABLE "users" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "addresses" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "password_reset_tokens" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "categories" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "products" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "product_images" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "carts" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "cart_items" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "orders" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "order_items" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "payments" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "reviews" ENABLE ROW LEVEL SECURITY;

-- ===== Storage buckets =====
INSERT INTO storage.buckets (id, name, public) VALUES ('product-images', 'product-images', true) ON CONFLICT (id) DO NOTHING;
INSERT INTO storage.buckets (id, name, public) VALUES ('payment-slips', 'payment-slips', false) ON CONFLICT (id) DO NOTHING;
