-- Gaming Gear E-Commerce schema (generated by apps/api/scripts/gen-sql.ts - do not edit by hand)
-- Run this whole file once in Supabase > SQL Editor on an empty database.
-- Seeded admin login: admin@gaminggear.local / admin1234

-- CreateSchema
CREATE SCHEMA IF NOT EXISTS "public";

-- CreateEnum
CREATE TYPE "Role" AS ENUM ('customer', 'admin');

-- CreateEnum
CREATE TYPE "OrderStatus" AS ENUM ('pending_payment', 'payment_review', 'processing', 'shipped', 'delivered', 'cancelled');

-- CreateEnum
CREATE TYPE "PaymentStatus" AS ENUM ('pending', 'approved', 'rejected');

-- CreateTable
CREATE TABLE "users" (
    "user_id" SERIAL NOT NULL,
    "full_name" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "password_hash" TEXT NOT NULL,
    "phone" TEXT,
    "role" "Role" NOT NULL DEFAULT 'customer',
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "users_pkey" PRIMARY KEY ("user_id")
);

-- CreateTable
CREATE TABLE "addresses" (
    "address_id" SERIAL NOT NULL,
    "user_id" INTEGER NOT NULL,
    "recipient_name" TEXT NOT NULL,
    "phone" TEXT NOT NULL,
    "address_line" TEXT NOT NULL,
    "is_default" BOOLEAN NOT NULL DEFAULT false,

    CONSTRAINT "addresses_pkey" PRIMARY KEY ("address_id")
);

-- CreateTable
CREATE TABLE "password_reset_tokens" (
    "token" TEXT NOT NULL,
    "user_id" INTEGER NOT NULL,
    "expires_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "password_reset_tokens_pkey" PRIMARY KEY ("token")
);

-- CreateTable
CREATE TABLE "categories" (
    "category_id" SERIAL NOT NULL,
    "category_name" TEXT NOT NULL,

    CONSTRAINT "categories_pkey" PRIMARY KEY ("category_id")
);

-- CreateTable
CREATE TABLE "products" (
    "product_id" SERIAL NOT NULL,
    "category_id" INTEGER,
    "sku" TEXT NOT NULL,
    "product_name" TEXT NOT NULL,
    "description" TEXT NOT NULL DEFAULT '',
    "price" DECIMAL(10,2) NOT NULL,
    "stock_quantity" INTEGER NOT NULL DEFAULT 0,
    "image_url" TEXT,
    "is_active" BOOLEAN NOT NULL DEFAULT true,

    CONSTRAINT "products_pkey" PRIMARY KEY ("product_id")
);

-- CreateTable
CREATE TABLE "carts" (
    "cart_id" SERIAL NOT NULL,
    "user_id" INTEGER NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "carts_pkey" PRIMARY KEY ("cart_id")
);

-- CreateTable
CREATE TABLE "cart_items" (
    "cart_item_id" SERIAL NOT NULL,
    "cart_id" INTEGER NOT NULL,
    "product_id" INTEGER NOT NULL,
    "quantity" INTEGER NOT NULL,

    CONSTRAINT "cart_items_pkey" PRIMARY KEY ("cart_item_id")
);

-- CreateTable
CREATE TABLE "orders" (
    "order_id" SERIAL NOT NULL,
    "user_id" INTEGER NOT NULL,
    "order_date" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "status" "OrderStatus" NOT NULL DEFAULT 'pending_payment',
    "shipping_name" TEXT NOT NULL,
    "shipping_phone" TEXT NOT NULL,
    "shipping_address" TEXT NOT NULL,
    "shipping_method" TEXT NOT NULL,
    "tracking_number" TEXT,
    "shipping_fee" DECIMAL(10,2) NOT NULL DEFAULT 0,

    CONSTRAINT "orders_pkey" PRIMARY KEY ("order_id")
);

-- CreateTable
CREATE TABLE "order_items" (
    "order_item_id" SERIAL NOT NULL,
    "order_id" INTEGER NOT NULL,
    "product_id" INTEGER NOT NULL,
    "quantity" INTEGER NOT NULL,
    "unit_price" DECIMAL(10,2) NOT NULL,

    CONSTRAINT "order_items_pkey" PRIMARY KEY ("order_item_id")
);

-- CreateTable
CREATE TABLE "payments" (
    "payment_id" SERIAL NOT NULL,
    "order_id" INTEGER NOT NULL,
    "payment_method" TEXT NOT NULL,
    "amount" DECIMAL(10,2) NOT NULL,
    "status" "PaymentStatus" NOT NULL DEFAULT 'pending',
    "proof_url" TEXT,
    "paid_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "payments_pkey" PRIMARY KEY ("payment_id")
);

-- CreateTable
CREATE TABLE "reviews" (
    "review_id" SERIAL NOT NULL,
    "user_id" INTEGER NOT NULL,
    "product_id" INTEGER NOT NULL,
    "rating" INTEGER NOT NULL,
    "comment" TEXT NOT NULL DEFAULT '',
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "reviews_pkey" PRIMARY KEY ("review_id")
);

-- CreateIndex
CREATE UNIQUE INDEX "users_email_key" ON "users"("email");

-- CreateIndex
CREATE UNIQUE INDEX "categories_category_name_key" ON "categories"("category_name");

-- CreateIndex
CREATE UNIQUE INDEX "products_sku_key" ON "products"("sku");

-- CreateIndex
CREATE UNIQUE INDEX "carts_user_id_key" ON "carts"("user_id");

-- CreateIndex
CREATE UNIQUE INDEX "cart_items_cart_id_product_id_key" ON "cart_items"("cart_id", "product_id");

-- CreateIndex
CREATE UNIQUE INDEX "reviews_user_id_product_id_key" ON "reviews"("user_id", "product_id");

-- AddForeignKey
ALTER TABLE "addresses" ADD CONSTRAINT "addresses_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("user_id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "password_reset_tokens" ADD CONSTRAINT "password_reset_tokens_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("user_id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "products" ADD CONSTRAINT "products_category_id_fkey" FOREIGN KEY ("category_id") REFERENCES "categories"("category_id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "carts" ADD CONSTRAINT "carts_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("user_id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "cart_items" ADD CONSTRAINT "cart_items_cart_id_fkey" FOREIGN KEY ("cart_id") REFERENCES "carts"("cart_id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "cart_items" ADD CONSTRAINT "cart_items_product_id_fkey" FOREIGN KEY ("product_id") REFERENCES "products"("product_id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "orders" ADD CONSTRAINT "orders_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("user_id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "order_items" ADD CONSTRAINT "order_items_order_id_fkey" FOREIGN KEY ("order_id") REFERENCES "orders"("order_id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "order_items" ADD CONSTRAINT "order_items_product_id_fkey" FOREIGN KEY ("product_id") REFERENCES "products"("product_id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "payments" ADD CONSTRAINT "payments_order_id_fkey" FOREIGN KEY ("order_id") REFERENCES "orders"("order_id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "reviews" ADD CONSTRAINT "reviews_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("user_id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "reviews" ADD CONSTRAINT "reviews_product_id_fkey" FOREIGN KEY ("product_id") REFERENCES "products"("product_id") ON DELETE CASCADE ON UPDATE CASCADE;


-- ===== Seed data =====
INSERT INTO "users" ("full_name", "email", "password_hash", "phone", "role") VALUES ('Admin', 'admin@gaminggear.local', '$2b$10$p4BeS2cHAeo8clpW0mwHtu/wYquQn4aL6rGWu4UFhA7Oeh41piKzy', '0800000000', 'admin') ON CONFLICT ("email") DO NOTHING;

INSERT INTO "categories" ("category_name") VALUES ('Mouse') ON CONFLICT DO NOTHING;
INSERT INTO "categories" ("category_name") VALUES ('Keyboard') ON CONFLICT DO NOTHING;
INSERT INTO "categories" ("category_name") VALUES ('Headset') ON CONFLICT DO NOTHING;
INSERT INTO "categories" ("category_name") VALUES ('Monitor') ON CONFLICT DO NOTHING;
INSERT INTO "categories" ("category_name") VALUES ('Chair') ON CONFLICT DO NOTHING;
INSERT INTO "categories" ("category_name") VALUES ('Controller') ON CONFLICT DO NOTHING;

INSERT INTO "products" ("category_id", "sku", "product_name", "description", "price", "stock_quantity") SELECT "category_id", 'MS-001', 'Logitech G Pro X Superlight 2', 'เมาส์ไร้สายน้ำหนักเบาเพียง 60 กรัม เซนเซอร์ HERO 2 ความละเอียดสูงสุด 32,000 DPI', 5290, 25 FROM "categories" WHERE "category_name" = 'Mouse' ON CONFLICT ("sku") DO NOTHING;
INSERT INTO "products" ("category_id", "sku", "product_name", "description", "price", "stock_quantity") SELECT "category_id", 'MS-002', 'Razer DeathAdder V3', 'เมาส์ทรง ergonomic ยอดนิยมสำหรับเกม FPS เซนเซอร์ Focus Pro 30K', 2690, 40 FROM "categories" WHERE "category_name" = 'Mouse' ON CONFLICT ("sku") DO NOTHING;
INSERT INTO "products" ("category_id", "sku", "product_name", "description", "price", "stock_quantity") SELECT "category_id", 'MS-003', 'Zowie EC2-C', 'เมาส์สายสำหรับ eSports ไม่ต้องลงไดรเวอร์ รูปทรงถนัดขวา', 2390, 0 FROM "categories" WHERE "category_name" = 'Mouse' ON CONFLICT ("sku") DO NOTHING;
INSERT INTO "products" ("category_id", "sku", "product_name", "description", "price", "stock_quantity") SELECT "category_id", 'MS-004', 'SteelSeries Aerox 3 Wireless', 'เมาส์ไร้สายกันน้ำกันฝุ่น IP54 ดีไซน์รังผึ้ง', 2990, 18 FROM "categories" WHERE "category_name" = 'Mouse' ON CONFLICT ("sku") DO NOTHING;
INSERT INTO "products" ("category_id", "sku", "product_name", "description", "price", "stock_quantity") SELECT "category_id", 'KB-001', 'Wooting 60HE+', 'คีย์บอร์ดแม่เหล็ก Hall Effect ปรับระยะกดได้ รองรับ Rapid Trigger', 7490, 10 FROM "categories" WHERE "category_name" = 'Keyboard' ON CONFLICT ("sku") DO NOTHING;
INSERT INTO "products" ("category_id", "sku", "product_name", "description", "price", "stock_quantity") SELECT "category_id", 'KB-002', 'Keychron Q1 Pro', 'คีย์บอร์ด 75% บอดี้อะลูมิเนียม Hot-swap เชื่อมต่อไร้สาย Bluetooth', 6590, 15 FROM "categories" WHERE "category_name" = 'Keyboard' ON CONFLICT ("sku") DO NOTHING;
INSERT INTO "products" ("category_id", "sku", "product_name", "description", "price", "stock_quantity") SELECT "category_id", 'KB-003', 'Razer Huntsman V3 Pro TKL', 'สวิตช์ Analog Optical ปรับจุด actuation ได้ พร้อมที่พักข้อมือ', 7990, 8 FROM "categories" WHERE "category_name" = 'Keyboard' ON CONFLICT ("sku") DO NOTHING;
INSERT INTO "products" ("category_id", "sku", "product_name", "description", "price", "stock_quantity") SELECT "category_id", 'KB-004', 'Logitech G715', 'คีย์บอร์ดไร้สาย TKL ไฟ RGB ดีไซน์น่ารัก พร้อมที่พักข้อมือแบบคลาวด์', 5490, 12 FROM "categories" WHERE "category_name" = 'Keyboard' ON CONFLICT ("sku") DO NOTHING;
INSERT INTO "products" ("category_id", "sku", "product_name", "description", "price", "stock_quantity") SELECT "category_id", 'HS-001', 'HyperX Cloud III', 'หูฟังเกมมิ่งใส่สบาย ไมค์ตัดเสียงรบกวน รองรับ DTS Spatial Audio', 3290, 30 FROM "categories" WHERE "category_name" = 'Headset' ON CONFLICT ("sku") DO NOTHING;
INSERT INTO "products" ("category_id", "sku", "product_name", "description", "price", "stock_quantity") SELECT "category_id", 'HS-002', 'SteelSeries Arctis Nova Pro', 'หูฟังระดับไฮเอนด์พร้อม GameDAC และ Active Noise Cancellation', 11900, 5 FROM "categories" WHERE "category_name" = 'Headset' ON CONFLICT ("sku") DO NOTHING;
INSERT INTO "products" ("category_id", "sku", "product_name", "description", "price", "stock_quantity") SELECT "category_id", 'HS-003', 'Razer BlackShark V2 Pro', 'หูฟังไร้สายสำหรับ eSports ไดรเวอร์ TriForce Titanium 50mm', 6990, 14 FROM "categories" WHERE "category_name" = 'Headset' ON CONFLICT ("sku") DO NOTHING;
INSERT INTO "products" ("category_id", "sku", "product_name", "description", "price", "stock_quantity") SELECT "category_id", 'MN-001', 'ASUS ROG Swift PG27AQDM', 'จอ OLED 27 นิ้ว 1440p 240Hz ความเร็วตอบสนอง 0.03ms', 32900, 4 FROM "categories" WHERE "category_name" = 'Monitor' ON CONFLICT ("sku") DO NOTHING;
INSERT INTO "products" ("category_id", "sku", "product_name", "description", "price", "stock_quantity") SELECT "category_id", 'MN-002', 'BenQ ZOWIE XL2546K', 'จอ TN 24.5 นิ้ว 240Hz เทคโนโลยี DyAc+ สำหรับเกม FPS', 16900, 7 FROM "categories" WHERE "category_name" = 'Monitor' ON CONFLICT ("sku") DO NOTHING;
INSERT INTO "products" ("category_id", "sku", "product_name", "description", "price", "stock_quantity") SELECT "category_id", 'MN-003', 'LG UltraGear 27GR95QE', 'จอ OLED 27 นิ้ว 240Hz สีสดคมชัด รองรับ G-Sync', 29900, 6 FROM "categories" WHERE "category_name" = 'Monitor' ON CONFLICT ("sku") DO NOTHING;
INSERT INTO "products" ("category_id", "sku", "product_name", "description", "price", "stock_quantity") SELECT "category_id", 'CH-001', 'Secretlab TITAN Evo', 'เก้าอี้เกมมิ่งพรีเมียม ปรับ lumbar support ในตัว วัสดุ NEO Hybrid Leatherette', 17900, 9 FROM "categories" WHERE "category_name" = 'Chair' ON CONFLICT ("sku") DO NOTHING;
INSERT INTO "products" ("category_id", "sku", "product_name", "description", "price", "stock_quantity") SELECT "category_id", 'CH-002', 'Anda Seat Kaiser 3', 'เก้าอี้เกมมิ่งไซซ์ใหญ่ ที่วางแขน 4D พนักพิงเอนได้ 160 องศา', 14900, 11 FROM "categories" WHERE "category_name" = 'Chair' ON CONFLICT ("sku") DO NOTHING;
INSERT INTO "products" ("category_id", "sku", "product_name", "description", "price", "stock_quantity") SELECT "category_id", 'CT-001', 'Xbox Wireless Controller', 'จอยไร้สายใช้ได้ทั้ง Xbox และ PC เชื่อมต่อ Bluetooth', 2190, 35 FROM "categories" WHERE "category_name" = 'Controller' ON CONFLICT ("sku") DO NOTHING;
INSERT INTO "products" ("category_id", "sku", "product_name", "description", "price", "stock_quantity") SELECT "category_id", 'CT-002', 'PlayStation DualSense Edge', 'จอยโปรสำหรับ PS5 ปุ่มหลังปรับแต่งได้ เปลี่ยนก้านอนาล็อกได้', 7590, 8 FROM "categories" WHERE "category_name" = 'Controller' ON CONFLICT ("sku") DO NOTHING;
INSERT INTO "products" ("category_id", "sku", "product_name", "description", "price", "stock_quantity") SELECT "category_id", 'CT-003', '8BitDo Ultimate 2', 'จอยไร้สายก้าน Hall Effect พร้อมแท่นชาร์จ รองรับ PC และ Switch', 2290, 20 FROM "categories" WHERE "category_name" = 'Controller' ON CONFLICT ("sku") DO NOTHING;
INSERT INTO "products" ("category_id", "sku", "product_name", "description", "price", "stock_quantity") SELECT "category_id", 'CT-004', 'Razer Wolverine V3 Pro', 'จอยสำหรับ Xbox/PC ปุ่ม Mecha-Tactile และ Trigger Stop', 6990, 3 FROM "categories" WHERE "category_name" = 'Controller' ON CONFLICT ("sku") DO NOTHING;

-- ===== Lock down the Supabase REST API =====
ALTER TABLE "users" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "addresses" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "password_reset_tokens" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "categories" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "products" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "carts" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "cart_items" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "orders" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "order_items" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "payments" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "reviews" ENABLE ROW LEVEL SECURITY;

-- ===== Storage buckets =====
INSERT INTO storage.buckets (id, name, public) VALUES ('product-images', 'product-images', true) ON CONFLICT (id) DO NOTHING;
INSERT INTO storage.buckets (id, name, public) VALUES ('payment-slips', 'payment-slips', false) ON CONFLICT (id) DO NOTHING;
