// Regenerates supabase/schema.sql from prisma/schema.prisma + seed data.
// Usage: npm run gen:sql -w apps/api
import * as bcrypt from 'bcryptjs';
import { execSync } from 'child_process';
import { writeFileSync } from 'fs';
import { join } from 'path';
import { ADMIN, CATEGORIES, PRODUCTS } from '../prisma/seed-data';

const q = (s: string) => `'${s.replace(/'/g, "''")}'`;

const ddl = execSync('npx prisma migrate diff --from-empty --to-schema-datamodel prisma/schema.prisma --script', {
  cwd: join(__dirname, '..'),
  encoding: 'utf8',
});

const seed = [
  '-- ===== Seed data =====',
  `INSERT INTO "users" ("full_name", "email", "password_hash", "phone", "role") VALUES (${q(ADMIN.fullName)}, ${q(ADMIN.email)}, ${q(bcrypt.hashSync(ADMIN.password, 10))}, ${q(ADMIN.phone)}, 'admin') ON CONFLICT ("email") DO NOTHING;`,
  '',
  ...CATEGORIES.map((c) => `INSERT INTO "categories" ("category_name") VALUES (${q(c)}) ON CONFLICT DO NOTHING;`),
  '',
  ...PRODUCTS.map(
    (p) =>
      `INSERT INTO "products" ("category_id", "sku", "product_name", "description", "price", "stock_quantity", "image_url") ` +
      `SELECT "category_id", ${q(p.sku)}, ${q(p.name)}, ${q(p.description)}, ${p.price}, ${p.stock}, ${q(p.imageUrl)} FROM "categories" WHERE "category_name" = ${q(p.category)} ON CONFLICT ("sku") DO NOTHING;`,
  ),
];

// The app only talks to Postgres through the NestJS API (as the `postgres` role, which bypasses RLS).
// Enabling RLS with no policies blocks Supabase's auto-generated REST API from reading these tables
// (e.g. password hashes) with the public anon key.
const TABLES = ['users', 'addresses', 'password_reset_tokens', 'categories', 'products', 'carts', 'cart_items', 'orders', 'order_items', 'payments', 'reviews'];
const security = [
  '',
  '-- ===== Lock down the Supabase REST API =====',
  ...TABLES.map((t) => `ALTER TABLE "${t}" ENABLE ROW LEVEL SECURITY;`),
  '',
  '-- ===== Storage buckets =====',
  `INSERT INTO storage.buckets (id, name, public) VALUES ('product-images', 'product-images', true) ON CONFLICT (id) DO NOTHING;`,
  `INSERT INTO storage.buckets (id, name, public) VALUES ('payment-slips', 'payment-slips', false) ON CONFLICT (id) DO NOTHING;`,
];
seed.push(...security);

const header =`-- Gaming Gear E-Commerce schema (generated by apps/api/scripts/gen-sql.ts - do not edit by hand)
-- Run this whole file once in Supabase > SQL Editor on an empty database.
-- Seeded admin login: ${ADMIN.email} / ${ADMIN.password}

`;

writeFileSync(join(__dirname, '../../../supabase/schema.sql'), header + ddl + '\n' + seed.join('\n') + '\n');
console.log('Wrote supabase/schema.sql');
